--!strict
-- Uploaded asset ids for original textures and audio created for The Spire.
-- Source files live in assets/ (generated by tools/ scripts); after uploading
-- them (Asset Manager or tools/upload_assets.py) paste the rbxassetid:// ids
-- here. Systems treat an empty id as "not uploaded yet" and fall back to a
-- built-in look (plain glowing water, no ambience loop) instead of erroring.

local AssetManifest = {
	Textures = {
		CurrentFlow = "", -- assets/textures/current_flow.png (seamless, scrolls on canal water)
		CurrentFalls = "", -- assets/textures/current_falls.png (scrolls down waterfall sheets)
	} :: { [string]: string },
	Ambience = {
		TownRain = "",
		Harbor = "",
		Marsh = "",
		Forest = "",
		Highland = "",
		Gate = "",
		Cave = "",
		Dungeon = "",
	} :: { [string]: string },
}

return AssetManifest
