--!strict
--[[
	KitManifestGuardians (generated by tools/blender/guardian/build_brinewarden.py; do not edit by hand)
	Floor Guardian body pieces from SpireKit_Guardians.fbx, in the KitManifest schema (Blender space:
	z up, the body faces -y, 1 unit = 1 stud). KitManifest merges these into its Files and Pieces, so
	KitLibrary.Prepare() builds a template for each piece once the FBX is imported.

	Each piece is rigid and rides one R15 part: Position is that part's centre in a reference rig at
	Meta.rigScale (Roblox default R15 x rigScale, feet on z = 0), so the template origin IS the limb
	centre. Like every kit piece the body faces template +Z, so MobService/Builder turns each piece
	180 degrees about Y onto its limb (an R15 part faces -Z). Meta: body (MobDef Body.MeshBody), limb
	(R15 part), role (Part name in the boss Model: Shell / Core / Seam / Claw / Helm / ...), rigScale,
	pieces (how many make the body), limbSize (studs, x y-up z), shadow, light.
]]

local HttpService = game:GetService("HttpService")

local DATA = [==[
{"Files":{"Guardians":{"meshes":108,"optional":1,"pieces":22,"tris":31322}},"Pieces":{"Brinewarden_Core":{"Anchors":{"Core":[0.0,-1.95,0.849,0.0]},"Bounds":[[-2.984,-2.781,-2.134],[2.874,-0.961,
3.581]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","light":{"brightness":2.2,"range":16},"limb":"UpperTorso","limbSize":[6.607,5.773,3.414],"pieces":22,
"rigScale":3.4,"role":"Core","shadow":false},"Position":[0.0,0.0,11.701],"Size":[5.858,1.82,5.715]},"Brinewarden_Head":{"Anchors":{"EyeL":[0.6,-2.15,0.25,0.0],"EyeR":[-0.6,-2.15,0.25,0.0]},
"Bounds":[[-3.747,-3.564,-2.05],[3.747,2.754,4.223]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","light":{"brightness":1.4,"range":9},"limb":"Head",
"limbSize":[3.941,4.019,3.946],"pieces":22,"rigScale":3.4,"role":"Helm","shadow":true},"Position":[0.0,0.0,16.545],"Size":[7.493,6.318,6.273]},"Brinewarden_LeftFoot":{"Anchors":{},"Bounds":[[-1.479,
-4.4,-0.56],[1.479,2.088,0.92]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"LeftFoot","limbSize":[3.43,1.061,3.404],"pieces":22,"rigScale":3.4,
"role":"Armor","shadow":false},"Position":[1.7,0.0,0.53],"Size":[2.959,6.488,1.479]},"Brinewarden_LeftHand":{"Anchors":{"Tip":[0.15,-7.714,-5.751,0.0]},"Bounds":[[-2.0,-8.307,-6.534],[2.138,1.95,
1.9]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"LeftHand","limbSize":[3.347,1.074,3.496],"pieces":22,"rigScale":3.4,"role":"Claw","shadow":true},
"Position":[5.005,0.0,7.91],"Size":[4.138,10.256,8.435]},"Brinewarden_LeftLowerArm":{"Anchors":{"Wrist":[0.0,0.0,-1.808,0.0]},"Bounds":[[-2.02,-2.681,-1.799],[2.656,2.182,1.761]],
"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"LeftLowerArm","limbSize":[3.404,3.799,3.406],"pieces":22,"rigScale":3.4,"role":"Armor","shadow":true},
"Position":[5.005,0.0,10.167],"Size":[4.676,4.862,3.56]},"Brinewarden_LeftLowerLeg":{"Anchors":{"Ankle":[0.0,0.0,-2.027,0.0]},"Bounds":[[-1.576,-2.667,-2.675],[1.792,3.029,2.658]],
"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"LeftLowerLeg","limbSize":[3.376,4.422,3.308],"pieces":22,"rigScale":3.4,"role":"Armor","shadow":true},
"Position":[1.7,0.0,2.919],"Size":[3.367,5.696,5.333]},"Brinewarden_LeftUpperArm":{"Anchors":{"Elbow":[0.0,0.0,-1.206,0.0]},"Bounds":[[-2.2,-2.609,-1.879],[2.356,2.609,2.283]],"Category":"Guardian",
"Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"LeftUpperArm","limbSize":[3.404,4.221,3.406],"pieces":22,"rigScale":3.4,"role":"Armor","shadow":true},"Position":[5.005,0.0,
12.308],"Size":[4.556,5.218,4.162]},"Brinewarden_LeftUpperLeg":{"Anchors":{"Knee":[0.0,0.0,-1.529,0.0]},"Bounds":[[-1.905,-3.346,-2.748],[2.056,1.773,2.162]],"Category":"Guardian","Collision":[],
"File":"Guardians","Meta":{"body":"Brinewarden","limb":"LeftUpperLeg","limbSize":[3.376,4.634,3.307],"pieces":22,"rigScale":3.4,"role":"Armor","shadow":true},"Position":[1.7,0.0,5.851],"Size":[3.961,
5.119,4.91]},"Brinewarden_LowerTorso":{"Anchors":{"HipL":[1.7,0.0,-0.68,0.0],"HipR":[-1.7,0.0,-0.68,0.0]},"Bounds":[[-7.38,-3.018,-4.882],[7.38,4.417,2.62]],"Category":"Guardian","Collision":[],
"File":"Guardians","Meta":{"body":"Brinewarden","limb":"LowerTorso","limbSize":[6.771,1.362,3.414],"pieces":22,"rigScale":3.4,"role":"Tassets","shadow":true},"Position":[0.0,0.0,8.134],"Size":[14.76,
7.435,7.502]},"Brinewarden_RightFoot":{"Anchors":{},"Bounds":[[-1.479,-4.4,-0.56],[1.479,2.088,0.92]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden",
"limb":"RightFoot","limbSize":[3.43,1.061,3.404],"pieces":22,"rigScale":3.4,"role":"Armor","shadow":false},"Position":[-1.7,0.0,0.53],"Size":[2.959,6.488,1.479]},"Brinewarden_RightHand":{"Anchors":{},
"Bounds":[[-1.85,-1.804,-1.152],[1.85,1.804,1.082]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"RightHand","limbSize":[3.347,1.074,3.496],"pieces":22,
"rigScale":3.4,"role":"Gauntlet","shadow":true},"Position":[-5.005,0.0,7.91],"Size":[3.7,3.607,2.235]},"Brinewarden_RightLowerArm":{"Anchors":{"Wrist":[0.0,0.0,-1.808,0.0]},"Bounds":[[-2.461,-1.66,
-1.843],[1.658,2.52,1.937]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"RightLowerArm","limbSize":[3.404,3.799,3.406],"pieces":22,"rigScale":3.4,
"role":"Armor","shadow":true},"Position":[-5.005,0.0,10.167],"Size":[4.119,4.18,3.781]},"Brinewarden_RightLowerLeg":{"Anchors":{"Ankle":[0.0,0.0,-2.027,0.0]},"Bounds":[[-1.792,-2.667,-2.682],[1.576,
3.029,2.669]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"RightLowerLeg","limbSize":[3.376,4.422,3.308],"pieces":22,"rigScale":3.4,"role":"Armor",
"shadow":true},"Position":[-1.7,0.0,2.919],"Size":[3.367,5.696,5.35]},"Brinewarden_RightUpperArm":{"Anchors":{"Elbow":[0.0,0.0,-1.206,0.0]},"Bounds":[[-2.081,-2.339,-1.872],[1.982,2.339,2.125]],
"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"RightUpperArm","limbSize":[3.404,4.221,3.406],"pieces":22,"rigScale":3.4,"role":"Armor","shadow":true},
"Position":[-5.005,0.0,12.308],"Size":[4.063,4.679,3.997]},"Brinewarden_RightUpperLeg":{"Anchors":{"Knee":[0.0,0.0,-1.529,0.0]},"Bounds":[[-2.056,-3.346,-2.779],[1.905,1.746,2.192]],
"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"RightUpperLeg","limbSize":[3.376,4.634,3.307],"pieces":22,"rigScale":3.4,"role":"Armor","shadow":true},
"Position":[-1.7,0.0,5.851],"Size":[3.961,5.092,4.971]},"Brinewarden_Seam":{"Anchors":{"Seam":[0.0,2.65,0.299,0.0]},"Bounds":[[-0.183,2.235,-1.839],[0.184,2.735,2.438]],"Category":"Guardian",
"Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","light":{"brightness":1.0,"range":8},"limb":"UpperTorso","limbSize":[6.607,5.773,3.414],"pieces":22,"rigScale":3.4,"role":"Seam",
"shadow":false},"Position":[0.0,0.0,11.701],"Size":[0.367,0.5,4.277]},"Brinewarden_ShellBack":{"Anchors":{},"Bounds":[[-4.422,0.015,-2.213],[4.422,3.412,3.287]],"Category":"Guardian","Collision":[],
"File":"Guardians","Meta":{"body":"Brinewarden","limb":"UpperTorso","limbSize":[6.607,5.773,3.414],"pieces":22,"rigScale":3.4,"role":"Shell","shadow":true},"Position":[0.0,0.0,11.701],"Size":[8.844,
3.398,5.5]},"Brinewarden_ShellChest":{"Anchors":{},"Bounds":[[-1.988,-3.462,-0.767],[1.988,-2.286,2.469]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden",
"limb":"UpperTorso","limbSize":[6.607,5.773,3.414],"pieces":22,"rigScale":3.4,"role":"Shell","shadow":true},"Position":[0.0,0.0,11.701],"Size":[3.975,1.176,3.237]},
"Brinewarden_ShellPauldronL":{"Anchors":{},"Bounds":[[-3.454,-4.449,-2.822],[6.262,4.549,4.763]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden",
"limb":"LeftUpperArm","limbSize":[3.404,4.221,3.406],"pieces":22,"rigScale":3.4,"role":"Shell","shadow":true},"Position":[5.005,0.0,12.308],"Size":[9.717,8.998,7.586]},
"Brinewarden_ShellPauldronR":{"Anchors":{},"Bounds":[[-3.513,-3.279,-0.809],[2.855,3.559,3.252]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden",
"limb":"RightUpperArm","limbSize":[3.404,4.221,3.406],"pieces":22,"rigScale":3.4,"role":"Shell","shadow":true},"Position":[-5.005,0.0,12.308],"Size":[6.368,6.838,4.061]},
"Brinewarden_Sword":{"Anchors":{"Pommel":[0.0,4.9,-0.322,0.0],"Tip":[0.0,-17.5,-0.322,0.0]},"Bounds":[[-1.399,-17.377,-4.012],[1.235,5.135,3.368]],"Category":"Guardian","Collision":[],
"File":"Guardians","Meta":{"body":"Brinewarden","light":{"brightness":1.2,"range":12},"limb":"RightHand","limbSize":[3.347,1.074,3.496],"pieces":22,"rigScale":3.4,"role":"Greatsword","shadow":true},
"Position":[-5.005,0.0,7.91],"Size":[2.634,22.513,7.379]},"Brinewarden_UpperTorso":{"Anchors":{"Core":[0.0,-1.95,0.849,0.0],"Neck":[0.0,0.0,2.887,0.0],"ShoulderL":[3.303,0.0,2.03,0.0],
"ShoulderR":[-3.303,0.0,2.03,0.0]},"Bounds":[[-3.566,-2.373,-2.903],[3.566,3.763,5.003]],"Category":"Guardian","Collision":[],"File":"Guardians","Meta":{"body":"Brinewarden","limb":"UpperTorso",
"limbSize":[6.607,5.773,3.414],"pieces":22,"rigScale":3.4,"role":"Carapace","shadow":true},"Position":[0.0,0.0,11.701],"Size":[7.132,6.136,7.906]}}}
]==]

return HttpService:JSONDecode(DATA)
