--!strict
--[[
	Strings
	Every player-facing string in the game. Nothing in UI or notifications
	may use a literal string; it reads from here so the game can be localized.
	Use Strings.Format("Hello {name}", { name = "Ash" }) for placeholders.
]]

local TableUtil = require(script.Parent.Util.TableUtil)

local Strings = {
	Game = {
		Title = "The Spire",
		Tagline = "Climb. Fight. Bend the Current.",
	},

	Actions = {
		Jump = "Jump",
		LightAttack = "Light Attack",
		HeavyAttack = "Heavy Attack",
		Dodge = "Dodge Roll",
		Block = "Block / Parry",
		LockOn = "Lock On",
		Sprint = "Sprint",
		Cast1 = "Spell 1",
		Cast2 = "Spell 2",
		Cast3 = "Spell 3",
		Cast4 = "Spell 4",
		WeaponArt = "Weapon Art / Confluence",
		Ability = "Position Ability",
		Interact = "Interact",
		Consumable1 = "Quick Item 1",
		Consumable2 = "Quick Item 2",
		Ping = "Ping Marker",
		Emote = "Emote Wheel",
		FreeCursor = "Free Cursor (hold)",
		OpenCharacter = "Character",
		OpenInventory = "Inventory",
		OpenSpellbook = "Spellbook",
		OpenSkillTree = "Skill Tree",
		OpenQuestLog = "Quest Log",
		OpenMap = "Map",
		OpenParty = "Party",
		OpenSettings = "Settings",
		OpenMenuHub = "Menu",
		CloseMenu = "Back",
		TabLeft = "Previous Tab",
		TabRight = "Next Tab",
		NavPrev = "Previous Page",
		NavNext = "Next Page",
		DevGallery = "UI Gallery",
	} :: { [string]: string },

	ActionCategories = {
		Combat = "Combat",
		Movement = "Movement",
		Magic = "Magic",
		Utility = "Utility",
		Menus = "Menus",
		Developer = "Developer",
	} :: { [string]: string },

	-- Short labels printed on mobile buttons.
	TouchLabels = {
		Attack = "ATK",
		Jump = "JUMP",
		Cast1 = "I",
		Cast2 = "II",
		Cast3 = "III",
		Cast4 = "IV",
		WeaponArt = "ART",
		Ability = "SKILL",
		Dodge = "ROLL",
		Block = "GUARD",
		LockOn = "LOCK",
		Interact = "USE",
		Consumable1 = "ITEM",
		Menu = "MENU",
	} :: { [string]: string },

	-- Display names for input names that read badly raw.
	KeyNames = {
		MouseButton1 = "LMB",
		MouseButton2 = "RMB",
		MouseButton3 = "MMB",
		LeftShift = "Shift",
		Tab = "TAB",
		RightShift = "R-Shift",
		LeftControl = "Ctrl",
		LeftAlt = "Alt",
		Backspace = "Bksp",
		One = "1",
		Two = "2",
		Three = "3",
		Four = "4",
		Five = "5",
		Six = "6",
		Seven = "7",
		Eight = "8",
		Nine = "9",
		Zero = "0",
		ButtonR1 = "RB",
		ButtonR2 = "RT",
		ButtonR3 = "RS",
		ButtonL1 = "LB",
		ButtonL2 = "LT",
		ButtonL3 = "LS",
		ButtonA = "A",
		ButtonB = "B",
		ButtonX = "X",
		ButtonY = "Y",
		ButtonSelect = "View",
		ButtonStart = "Menu",
		DPadUp = "D-Up",
		DPadDown = "D-Down",
		DPadLeft = "D-Left",
		DPadRight = "D-Right",
	} :: { [string]: string },

	Data = {
		LoadFailedKick = "We couldn't load your Climber's data. Please rejoin in a moment - nothing was lost.",
		SessionTakenKick = "Your Climber was loaded on another server. Rejoin to continue there.",
		ShuttingDown = "The Spire is shifting (server update). Rejoin to continue climbing.",
		OutdatedServer = "This server runs an older build of The Spire. Rejoin to reach an up-to-date server.",
		KickedExploit = "Disconnected: unusual network activity was detected.",
		Loading = "Gathering your Current...",
		SettingsSaved = "Settings saved",
	},

	UI = {
		Close = "Close",
		QuestsLater = "Your quests are in the Quest Log.",
		IconCredit = "Icons: game-icons.net (CC BY 3.0)",
		Back = "Back",
		Confirm = "Confirm",
		Cancel = "Cancel",
		Yes = "Yes",
		No = "No",
		On = "On",
		Off = "Off",
		Search = "Search...",
		PressAKey = "Press a key...",
		Unbound = "-",
		KeyConflict = "{key} was moved from {other}.",
		KeyReserved = "{key} is reserved and can't be bound.",
		Locked = "Locked",
	},

	Toasts = {
		Welcome = "Welcome to The Spire, {name}.",
		DataReady = "Progress loaded",
		WaystoneDiscovered = "Waystone discovered: {name}",
		WaystoneRested = "Rested at {name}. You will return here if you fall.",
		LostCurrentDropped = "{gold} gold slipped into the Current where you fell.",
		LostCurrentRecovered = "Recovered {gold} gold from your Lost Current.",
		LostCurrentGone = "Your earlier Lost Current dissolved.",
		Winded = "Winded",
		KillRewards = "+{xp} XP",
		LevelUp = "Level {level} reached: +{points} stat points",
		LevelUpSkill = "Level {level} reached: +{points} stat points, +{skill} skill point",
		LevelUpSkills = "Level {level} reached: +{points} stat points, +{skill} skill points",
		PositionsUnlocked = "Level {level}: visit the Hall of Positions in Lowharbor to choose your Position.",
		DiscoveryXP = "Discovery: +{xp} XP",
		SecretFound = "Secret found: {name}",
		CacheOpened = "You opened a hidden cache. +{gold} gold",
		CacheEmpty = "You have already emptied this cache.",
		DungeonGathering = "Gathering for the Sunken Cistern: {count}/{max}. Others can step in now.",
		DungeonLevel = "The Cistern's seal will not yield below level {level}.",
		DungeonFull = "Every Cistern is in use. Try again in a moment.",
		LeverPulled = "A sluice lever groans into place. {left} to go.",
		SluiceOpened = "The sluice gate rises.",
		ChestSealed = "The hoard is sealed while the Cistern's guardians remain.",
		ChestUnsealed = "The hoard's seal breaks.",
		DungeonCleared = "Sunken Cistern cleared!",
		PositionChosen = "You are a {name} now. Press {key} to open your skill tree.",
		NodeUnlocked = "{name} learned",
		AbilityEquipped = "{name} is on your ability key",
		Respecced = "Your Current settles anew: every point is yours to spend again.",
		StatsSpent = "Attributes raised",
		AbilityCooldown = "{name} is recovering",
		Attuned = "Attuned to {name}. The Current answers you.",
		FormLearned = "New spell Form learned: {form}",
		NoCurrent = "Not enough Current",
		Overflow = "Overflow! Your spells surge.",
		Burnout = "Burnout. Casting slows for a moment.",
		ShrineNeedsLevel = "The Shrine stays silent. Return at level {level}.",
		ShrineDone = "You carry every Attunement you can for now.",
		Infused = "{name} Infusion: your blade carries the Current.",
		NeedAttunement = "Attune at the Shrine first.",
		ArtCooldown = "{name} is recovering",
		ConfluenceReady = "Resonance full: Confluence ready!",
		Relay = "Relay recast {spell}",
		BeaconSet = "Beacon {slot}: {name}",
		RecipeLearned = "Recipe learned: {name}",
		RecipesLearned = "{count} recipes learned",
		CoreSlotted = "{name} slotted: your Beacons answer to it now.",
		CoreRemoved = "Beacon core removed",
		Overburdened = "Overburdened: you can't sprint.",
		BagFull = "Your bag is full: loot stays on the ground for a while.",
		Durability = "Your gear wore down. Repair it at a Forge or Armorer's Bench.",
		Broken = "{name} broke: half stats until repaired.",
		ItemUsed = "{name}",
		BuffStarted = "{name}: {seconds}s",
		ItemEquipped = "Equipped {name}",
	},

	HUD = {
		Level = "{level}",
		XP = "{xp} / {next} XP",
		XPMax = "Max level",
		HealthValue = "{current} / {max}",
	},

	Death = {
		Title = "Your Current fades",
		Subtitle = "The Spire remembers. Rise again.",
		Respawn = "Respawn at Waystone",
		RespawnIn = "Respawn in {seconds}",
	},

	Prompts = {
		Rest = "Rest",
		OpenCache = "Open",
		CacheObject = "Hidden Cache",
		Pickup = "Pick up",
		Tap = "TAP",
		Attune = "Attune",
		Shrine = "Attunement Shrine",
	},

	-- The Current: Attunements (elements), Forms (spell shapes), statuses.
	Attunements = {
		Tide = { Name = "Tide", Description = "Drenching water. Hits leave enemies Soaked and slowed; Tide detonates Rooted foes." },
		Rime = { Name = "Rime", Description = "Biting frost. Each hit Chills; four Chills freeze an enemy solid." },
		Tempest = { Name = "Tempest", Description = "Storm lightning. Shocked enemies spread your bolts; detonates Soaked foes." },
		Abyss = { Name = "Abyss", Description = "Crushing depth. Heavy enemies take more of every blow; detonates Chilled foes." },
		Bloom = { Name = "Bloom", Description = "Living growth. Roots enemies in place, and your Wards and Wells heal." },
	} :: { [string]: { Name: string, Description: string } },
	Forms = {
		Bolt = { Name = "Bolt", Description = "A fast bolt at your target." },
		Wave = { Name = "Wave", Description = "A cone that strikes everything in front of you." },
		Ward = { Name = "Ward", Description = "A shield that absorbs damage and marks those who strike it." },
		Lance = { Name = "Lance", Description = "Hold to charge, release to fire a beam that pierces every enemy in a line." },
		Well = { Name = "Well", Description = "A pool that pulses at the spot you aim." },
		Step = { Name = "Step", Description = "Blink forward, untouchable for a breath, and burst where you land." },
	} :: { [string]: { Name: string, Description: string } },
	Statuses = {
		Soaked = "Soaked",
		Chilled = "Chilled",
		Frozen = "Frozen",
		Shocked = "Shocked",
		Heavy = "Heavy",
		Rooted = "Rooted",
		Renewing = "Renewing",
	} :: { [string]: string },
	SpellUI = {
		ShrineTitle = "Attunement Shrine",
		ShrinePrimary = "Choose the element your Current will carry.",
		ShrineSecondary = "Choose a second element to carry alongside {name}.",
		Choose = "Attune",
		Close = "Not yet",
		Empty = "-",
		Art = "ART",
		Confluence = "CONFLUENCE",
	},

	-- Spellbook menu (K).
	Spellbook = {
		Title = "Spellbook",
		TabArts = "Arts",
		TabBeacons = "Beacons",
		NotAttuned = "Your Current has no element yet. Visit the Attunement Shrine in Climbers' Rest at level {level}.",
		LockedTab = "Unlocks at level {level} at the Attunement Shrine.",
		UnlocksAt = "Unlocks at level {level}",
		Cost = "{cost} Current",
		Cooldown = "{seconds}s cooldown",
		CastTime = "{seconds}s cast",
		Charge = "Charge up to {seconds}s",
		Scaling = "Scales with Density; Control speeds it up and lowers its cost",
		Hotbar = "Hotbar",
		HotbarHint = "Drag a spell onto a slot, or select a spell and then a slot.",
		Selected = "Now choose a slot for {spell}",
		Primary = "Primary",
		Secondary = "Secondary",
		WeaponArt = "Weapon Art",
		Infusion = "Infusion",
		InfusionBody = "Hold {key} for a moment: your blade carries {element} for {seconds}s. Sword hits apply {status} and draw 50% more Current. Costs {cost} Current.",
		InfusionLocked = "Hold the Weapon Art button to Infuse your blade once you are attuned.",
		ConfluenceTitle = "Confluences",
		ConfluenceBody = "Weave sword hits and spells to fill Resonance. At full Resonance, {key} unleashes your weapon's Confluence with your primary element ({cost} Current, {seconds}s cooldown).",
		YourConfluence = "Your Confluence",
		BeaconSlots = "Beacon slots: {count} of {max}",
		BeaconSlotLocked = "More slots open at {points} Control",
		BeaconLocked = "Beacons are shaped Current: attune at the Shrine to call them.",
		BeaconEmpty = "Empty",
		BeaconSlot = "Slot {slot}",
		Choose = "Choose",
	},

	-- Weapon Arts, keyed by weapon class.
	Arts = {
		Longsword = { Name = "Rising Arc", Description = "A launcher slash that throws light enemies into the air." },
		Greatblade = { Name = "Crater", Description = "Leap and smash down, sending out a shockwave. Hits can't stop it." },
		Twinfangs = { Name = "Whirl", Description = "A spinning dash that cuts everything in your path twice." },
		SpireLance = { Name = "Skewer Rush", Description = "Charge forward and pierce every enemy in a line." },
		Needle = { Name = "Thousand Points", Description = "Six lightning-fast thrusts, each likelier to crit." },
		Arcblade = { Name = "Edge Release", Description = "Fire the blade's Current as a piercing crescent wave." },
	} :: { [string]: { Name: string, Description: string } },

	-- Confluences, keyed "<Class>_<Attunement>".
	Confluences = {
		Longsword_Tide = { Name = "Riptide Verdict", Description = "A rising slash, then the planted blade bursts into a ring wave that hurls enemies back." },
		Longsword_Rime = { Name = "Glacier Oath", Description = "A rising slash, then a ring of ice freezes everything around you and erupts into spikes." },
		Longsword_Tempest = { Name = "Thunderwake", Description = "A rising slash calls three bolts onto nearby enemies, ending in a thunderclap." },
		Longsword_Abyss = { Name = "Nightfall Edict", Description = "A rising slash drags enemies into a collapsing pit of weight." },
		Longsword_Bloom = { Name = "Verdant Oath", Description = "A rising slash plants a blooming circle that heals allies and roots enemies." },
		Greatblade_Tide = { Name = "Tidebreaker", Description = "Leap and slam, releasing a towering wave that crashes forward and drags enemies with it." },
		Greatblade_Rime = { Name = "Avalanche Fall", Description = "Leap and slam, then a wide ring of ice spikes chills everything twice." },
		Greatblade_Tempest = { Name = "Skyfall Hammer", Description = "Leap and slam, calling a lightning column that arcs to nearby enemies." },
		Greatblade_Abyss = { Name = "Gravity Crater", Description = "Leap and slam, opening a crater that pulls enemies in before it implodes." },
		Greatblade_Bloom = { Name = "Rootquake", Description = "Leap and slam; roots erupt in a line ahead and the Current mends you." },
		Twinfangs_Tide = { Name = "Undertow Dance", Description = "Blink between four enemies, then a whirlpool drags them together and bursts." },
		Twinfangs_Rime = { Name = "Hailstep Waltz", Description = "Blink between five enemies; the frost you leave on each one shatters at once." },
		Twinfangs_Tempest = { Name = "Stormdance", Description = "Blink between up to six enemies, slashing each, ending with a lightning crack overhead." },
		Twinfangs_Abyss = { Name = "Umbral Flurry", Description = "Blink between five enemies, then drag every one of them into a crushing collapse." },
		Twinfangs_Bloom = { Name = "Thornwaltz", Description = "Blink between five enemies, drinking their Current, and leave a healing thicket behind." },
		SpireLance_Tide = { Name = "Harpoon Surge", Description = "Hurl the spear through a line of enemies and reel every one of them back to you." },
		SpireLance_Rime = { Name = "Icicle Javelin", Description = "Hurl the spear through a line of enemies; where it lands, everything freezes." },
		SpireLance_Tempest = { Name = "Stormpike", Description = "The hurled spear becomes a lightning rod that calls four strikes around it." },
		SpireLance_Abyss = { Name = "Gravespear", Description = "The hurled spear becomes a gravity well, pulls enemies in, then collapses." },
		SpireLance_Bloom = { Name = "Seedspear", Description = "The hurled spear takes root: a grove that heals allies and roots enemies." },
		Needle_Tide = { Name = "Piercing Current", Description = "A certain thrust that fires a water jet straight through the line behind." },
		Needle_Rime = { Name = "Frostbloom", Description = "A certain thrust freezes the target and grows ice spikes; your next hit shatters them." },
		Needle_Tempest = { Name = "Arc Needle", Description = "A certain thrust that sends lightning leaping to four more enemies." },
		Needle_Abyss = { Name = "Hollow Point", Description = "A certain thrust plants a singularity that detonates a moment later." },
		Needle_Bloom = { Name = "Thornheart", Description = "A certain thrust that roots the target and heals you for most of the damage." },
		Arcblade_Tide = { Name = "Overcurrent: Tide", Description = "Three crescent waves fan out and hurl every enemy they cut away from you." },
		Arcblade_Rime = { Name = "Overcurrent: Rime", Description = "Three crescent waves fan out, chilling twice and leaving a field of frost." },
		Arcblade_Tempest = { Name = "Overcurrent: Tempest", Description = "Three crescent waves fan out, and lightning jumps from everything they cut." },
		Arcblade_Abyss = { Name = "Overcurrent: Abyss", Description = "Three crescent waves fan out, then fold into a pit that drags enemies in." },
		Arcblade_Bloom = { Name = "Overcurrent: Bloom", Description = "Three crescent waves fan out and wash over your allies with healing." },
	} :: { [string]: { Name: string, Description: string } },

	-- Beacon behaviours (Spec Section 6).
	Beacons = {
		Sentry = { Name = "Sentry", Description = "Fires small Bolts at enemies while you fight." },
		Aegis = { Name = "Aegis", Description = "Absorbs one hit completely, then breaks and slowly re-forms." },
		Lantern = { Name = "Lantern", Description = "Lights the area and reveals hidden chests and invisible enemies." },
		Relay = { Name = "Relay", Description = "Stores the last spell you cast and recasts it for free when you parry." },
	} :: { [string]: { Name: string, Description: string } },

	-- Current Pressure (Spec Section 6).
	Pressure = {
		Label = "Pressure {level}",
		High = "High Pressure: spells hit harder and Current refills faster.",
		Low = "Low Pressure: sword blows hit harder and Siphon draws more, but Current refills slowly.",
		Neutral = "Neutral Pressure.",
	},

	-- Floating combat text (damage numbers show the number itself).
	Combat = {
		Reaction = "REACTION",
		Reactions = {
			Surge = "SURGE",
			Shatter = "SHATTER",
			Crush = "CRUSH",
		} :: { [string]: string },
		Absorbed = "ABSORBED",
		Parry = "PARRY",
		Blocked = "BLOCKED",
		Dodge = "DODGE",
		PerfectDodge = "PERFECT DODGE",
		Broken = "BROKEN",
		Riposte = "RIPOSTE",
		Finisher = "FINISHER",
		GuardBreak = "GUARD BREAK",
		NoStamina = "No stamina",
	},

	-- Item text, keyed by item DefId (Shared.Data.Items): Name, Description
	-- (what it does) and Flavor (a line of world texture, shown in italics).
	Items = {
		-- Weapons
		ClimbersLongsword = { Name = "Climber's Longsword", Description = "Plain, honest steel. Every Climber starts with one.", Flavor = "The guild stamps a number on the tang. Nobody remembers who carried yours before." },
		StonejawGreatblade = { Name = "Stonejaw Greatblade", Description = "A slab of quarried iron. Heavy blows shrug off hits.", Flavor = "Cut from the same cliff Lowharbor clings to." },
		BrinecutTwinfangs = { Name = "Brinecut Twinfangs", Description = "Twin salt-etched knives. Quick cuts draw extra Current.", Flavor = "Dockhands swear the salt keeps the edges hungry." },
		SpirewatchLance = { Name = "Spirewatch Lance", Description = "The longest reach on Floor 1. Thrust out of a roll.", Flavor = "Issued to the watch that stares up at the next floor every night." },
		GleamNeedle = { Name = "Gleam Needle", Description = "A thin, bright blade. Ripostes always find a gap.", Flavor = "Light enough to forget you are holding it, until it matters." },
		RuneedgeArcblade = { Name = "Runeedge Arcblade", Description = "Etched with channels for the Current. Hits quicken spells.", Flavor = "The runes hum louder the closer you stand to a canal." },
		TideforgedLongsword = { Name = "Tideforged Longsword", Description = "A harbor smith's answer to the Climber's blade: longer, keener, quenched in a canal.", Flavor = "Folded beneath a falling canal so the Current set into the steel." },
		LanternedgeArcblade = { Name = "Lanternedge Arcblade", Description = "An arcblade whose runes hold a warm, steady glow.", Flavor = "Lamplighters carry them on the night shift, for more than the light." },
		Wispfangs = { Name = "Wispfangs", Description = "Paired blades that catch the marshlight and keep a little of it.", Flavor = "Two lights went into the reeds. Two blades came out." },
		CisternGreatblade = { Name = "Cistern Greatblade", Description = "A heavy relic hauled out of the Sunken Cistern, still cold to the touch.", Flavor = "Whatever it was built to hold back, it held." },
		SaltglassNeedle = { Name = "Saltglass Needle", Description = "A needle of salt-hardened glass that never dulls and never breaks.", Flavor = "Grown, not forged, in the brine pools below the cliffs." },
		Tidecleaver = { Name = "Tidecleaver", Description = "The Brinewarden's coral greatsword, cut down to a Climber's grip. Its edge glows with the tide.", Flavor = "It was never meant to be lifted by one who yields." },
		TidekeepersPromise = { Name = "Tidekeeper's Promise", Description = "The lance of the last Tidekeeper. Its blows gather into a returning tide.", Flavor = "\"The tide always comes back.\" She did not." },

		-- Armor
		HarborHood = { Name = "Harbor Hood", Description = "A waxed hood with a brass-stitched brim.", Flavor = "Rain slides off it. Most other things don't." },
		HarborCoat = { Name = "Harbor Coat", Description = "A sturdy dockworker's coat reinforced with shell plates.", Flavor = "Made for weather that never ends." },
		HarborLeggings = { Name = "Harbor Leggings", Description = "Durable trousers for climbing wet stone.", Flavor = "Salt has softened every seam." },
		HarborGloves = { Name = "Harbor Gloves", Description = "Gloves that hold fast to slick rope and slicker grips.", Flavor = "A good grip has saved more Climbers than any sword." },
		HarborCloak = { Name = "Harbor Cloak", Description = "A woven cloak lined with a thread of Current.", Flavor = "The rain sounds far away beneath it." },
		TidewardenHelm = { Name = "Tidewarden Helm", Description = "A teal-enamelled helm of the old canal wardens.", Flavor = "The visor slits are shaped like waves breaking." },
		TidewardenMail = { Name = "Tidewarden Mail", Description = "Overlapping scale mail that sheds blows like water.", Flavor = "Each scale was once a coin paid to the wardens. They spent them well." },
		TidewardenGreaves = { Name = "Tidewarden Greaves", Description = "Greaves built for standing firm in a flooding canal.", Flavor = "Wardens never retreated. They waited for the water to." },
		TidewardenGauntlets = { Name = "Tidewarden Gauntlets", Description = "Articulated gauntlets with a sure, steady grip.", Flavor = "Knuckles worn smooth from hauling people out of the canals." },
		TidewardenMantle = { Name = "Tidewarden Mantle", Description = "A deep-teal mantle woven with Current thread.", Flavor = "In storms it ripples against the wind." },
		BrinewardenCarapace = { Name = "Brinewarden Carapace", Description = "Coral-red plate grown over a crab-knight's chest. Heavy, and nearly unbreakable.", Flavor = "It still smells of the deep." },

		-- Accessories
		PearlRing = { Name = "Pearl Ring", Description = "A simple ring set with a tide pearl. Your Vessel holds a little more.", Flavor = "A promise worn on one finger." },
		CoralBand = { Name = "Coral Band", Description = "A silver band set with red coral. Your blows find weak points.", Flavor = "Coral grows where the water is fiercest." },
		BrassAmulet = { Name = "Brass Amulet", Description = "A ward against the drowned dark.", Flavor = "Polished by a hundred nervous thumbs." },
		LanternPendant = { Name = "Lantern Pendant", Description = "A tiny lantern on a chain. The Current refills faster near your heart.", Flavor = "It never needs oil. Nobody asks why." },

		-- Consumables
		HealingDraught = { Name = "Healing Draught", Description = "Restores 35% of your health.", Flavor = "A warm breath against the cold." },
		CurrentTonic = { Name = "Current Tonic", Description = "Restores 40% of your Current.", Flavor = "A tide small enough to carry." },
		MarshStew = { Name = "Marsh Stew", Description = "For 3 minutes: +25% stamina regeneration and +10 max stamina.", Flavor = "Best eaten without asking what's in it." },
		PearlBroth = { Name = "Pearl Broth", Description = "For 3 minutes: +20% Current regeneration and +10 max Current.", Flavor = "Simmered with a pearl that is taken out again. Usually." },
		BrineBomb = { Name = "Brine Bomb", Description = "Throw it where you aim: a burst of brine that damages and Soaks everything nearby.", Flavor = "Shell, scrap and a pearl's worth of angry seawater." },

		-- Materials
		IronScrap = { Name = "Iron Scrap", Description = "Weathered iron. The Forge's everyday metal; also used for upgrades.", Flavor = "The harbor gives nothing away forever." },
		MarshFiber = { Name = "Marsh Fiber", Description = "Tough reed fibre for cloth, rope and stew.", Flavor = "Even flooded roots hold fast." },
		Rustwood = { Name = "Rustwood", Description = "Dense red wood for hafts and grips.", Flavor = "The grain remembers every storm." },
		BrineShell = { Name = "Brine Shell", Description = "Hardened carapace used for armour plates.", Flavor = "A small shelter from a vast sea." },
		TidePearl = { Name = "Tide Pearl", Description = "A bead of condensed Current, prized by smiths and alchemists.", Flavor = "Hold it to your ear: an ocean turns inside." },
		WispEssence = { Name = "Wisp Essence", Description = "Living marshlight for the Current Loom.", Flavor = "It leans toward your heartbeat." },
		SpireIngot = { Name = "Spire Ingot", Description = "Iron fused with tide pearls. Needed for upgrades past +6.", Flavor = "Smiths say it sings when it cools." },
		WardenShellFragment = { Name = "Warden Shell Fragment", Description = "A shard of the Brinewarden's coral-red armour.", Flavor = "Still warm, as if the crab-knight were watching." },
		BrinewardensPearl = { Name = "Brinewarden's Pearl", Description = "A bone-pale pearl that pulses with deep Current. Dropped by the Brinewarden.", Flavor = "It held the tide in place for a hundred years." },

		-- Beacon cores
		BrineCore = { Name = "Brine Core", Description = "Slot it to turn your Beacons sea-green. Sentry shots deal 20% more damage.", Flavor = "It hums like surf on stone." },
		PearlCore = { Name = "Pearl Core", Description = "Slot it to turn your Beacons pearl-white. Aegis re-forms 25% faster.", Flavor = "Smooth as a promise kept." },
		EchoCore = { Name = "Echo Core", Description = "Slot it to turn your Beacons violet. Relay recasts 25% sooner.", Flavor = "Whisper into it and it whispers back, a moment late." },
		WardensTideCore = { Name = "Warden's Tide Core", Description = "Slot it to turn your Beacons tide-teal. Sentry shots deal 25% more damage and Aegis re-forms 20% faster.", Flavor = "It keeps the Warden's patient rhythm." },

		-- Blueprints and quest items
		TideforgedBlueprint = { Name = "Tideforged Blueprint", Description = "Use to learn the Tideforged Longsword recipe at the Forge.", Flavor = "Written in a smith's careful, salt-stained hand." },
		TidewardenPattern = { Name = "Tidewarden Pattern", Description = "Use to learn the full Tidewarden armour set at the Armorer's Bench.", Flavor = "The wardens' last tailor left the measurements for whoever came next." },
		BrineSigil = { Name = "Brine Sigil", Description = "A summoning sigil. Offer it at the drowned altar in the depths of the Sunken Cistern.", Flavor = "Something beneath the harbor has been waiting to be called." },
	} :: { [string]: { Name: string, Description: string, Flavor: string } },

	-- The Character page of the Character window (TAB).
	CharacterSheet = {
		Details = "Character Details",
		BuildStats = "Build Stats",
		TheCurrent = "The Current",
		AllStats = "All Stats",
		ViewAll = "View all stats",
		BackToSummary = "Back to summary",
		LevelLabel = "Level",
		PositionLabel = "Position",
		TimeClimbed = "Time climbed",
		Kills = "Enemies defeated",
		PlaytimeFormat = "{hours}h {minutes}m",
		CurrentRegen = "Regeneration",
		SpellPower = "Spell power",
		CastSpeed = "Cast speed",
		SpellArea = "Spell area",
		PerSecond = "{value} / s",
		NoAttunement = "Not attuned yet. Visit the Attunement Shrine.",
		BeaconCore = "Beacon Core",
		EmptySlotHint = "Click to find {slot} gear in your bag.",
		EmptyCoreHint = "Slot a Beacon core from your bag (right-click it).",
		StatBreakdown = "{total}  ({base} + {gear} gear + {tree} skills)",
	},

	Inventory = {
		InventoryTitle = "Inventory",
		CharacterTitle = "Character",
		Search = "Search items...",
		SortName = "Name",
		SortRarity = "Rarity",
		SortType = "Type",
		SortNewest = "Newest",
		Sort = "Sort: {name}",
		Filters = {
			All = "All",
			New = "New",
			Weapon = "Weapons",
			Armor = "Armor",
			Accessory = "Accessories",
			Consumable = "Consumables",
			Material = "Materials",
			Other = "Other",
		} :: { [string]: string },
		Slots = "{used} / {max} slots",
		Weight = "Weight {weight} / {max}",
		Overburdened = "Overburdened: you can't sprint and walk slower.",
		Gold = "Gold",
		Shards = "Spire Shards",
		FloorTokens = "Floor {floor} Tokens",
		Empty = "Empty",
		EmptyBag = "Nothing here yet. Defeat enemies and open chests to fill your bag.",
		NoMatches = "No items match.",
		SelectHint = "Select an item to see it here.",
		DragHint = "Drag gear onto a slot to equip it. Right-click (or long-press) any item for more.",
		Equipped = "Equipped",
		Compare = "Compared with your {name}",
		Locked = "Locked",
		Quantity = "How many?",
		Confirm = "Confirm",
		Cancel = "Cancel",

		-- Context menu / buttons
		Equip = "Equip",
		EquipTo = "Equip to {slot}",
		Unequip = "Unequip",
		Use = "Use",
		Learn = "Learn recipe",
		SlotCore = "Slot in Beacons",
		UnslotCore = "Remove from Beacons",
		Quick1 = "Set as Quick Item 1",
		Quick2 = "Set as Quick Item 2",
		Split = "Split stack",
		Lock = "Lock",
		Unlock = "Unlock",
		Salvage = "Salvage",
		Track = "Track materials",
		Untrack = "Stop tracking",

		-- Equipment slot names
		SlotNames = {
			Weapon = "Weapon",
			Head = "Head",
			Chest = "Chest",
			Legs = "Legs",
			Hands = "Hands",
			Cloak = "Cloak",
			Ring1 = "Ring",
			Ring2 = "Ring",
			Amulet = "Amulet",
			Ring = "Ring",
		} :: { [string]: string },
		TypeNames = {
			Weapon = "Weapon",
			Armor = "Armor",
			Accessory = "Accessory",
			BeaconCore = "Beacon Core",
			Consumable = "Consumable",
			Material = "Material",
			Quest = "Quest Item",
			Blueprint = "Blueprint",
		} :: { [string]: string },
		ClassNames = {
			Longsword = "Longsword",
			Greatblade = "Greatblade",
			Twinfangs = "Twinfangs",
			SpireLance = "Spire Lance",
			Needle = "Needle",
			Arcblade = "Arcblade",
		} :: { [string]: string },
		StatNames = {
			Vitality = "Vitality",
			Endurance = "Endurance",
			Strength = "Strength",
			Finesse = "Finesse",
			Draw = "Draw",
			Density = "Density",
			Control = "Control",
		} :: { [string]: string },

		-- Tooltip lines
		Subtitle = "{rarity} {type}",
		WeaponSubtitle = "{rarity} {class}",
		Damage = "Damage {value}",
		Posture = "Posture {value}",
		Armor = "Armor {value}%",
		StatLine = "+{value} {stat}",
		Durability = "Durability {value} / {max}",
		Broken = "Broken: half stats until repaired",
		RequiredLevel = "Requires level {level}",
		Upgrade = "+{level}",
		SellValue = "Sells for {gold} gold",
		CantSell = "Can't be sold",
		StackOf = "Stack of {count}",
		Unique = "Unique: {name}",

		-- Affix lines ({value} is already formatted: "6", "0.5"...)
		Affixes = {
			WeaponDamage = "+{value}% weapon damage",
			CritChance = "+{value}% critical chance",
			PostureDamage = "+{value}% posture damage",
			Siphon = "Siphon +{value}%",
			TideDamage = "+{value}% Tide damage",
			RimeDamage = "+{value}% Rime damage",
			TempestDamage = "+{value}% Tempest damage",
			AbyssDamage = "+{value}% Abyss damage",
			BloomDamage = "+{value}% Bloom damage",
			MaxHealth = "+{value} max health",
			Armor = "+{value}% armor",
			MaxStamina = "+{value} max stamina",
			StaminaRegen = "+{value}% stamina regeneration",
			ParryWindow = "Parry window +{value} frame",
			ResonanceDecay = "Resonance decays {value} s slower",
			MaxCurrent = "+{value} max Current",
			CurrentRegen = "+{value}% Current regeneration",
			CastSpeed = "+{value}% cast speed",
			Vitality = "+{value} Vitality",
			Endurance = "+{value} Endurance",
			Strength = "+{value} Strength",
			Finesse = "+{value} Finesse",
			Draw = "+{value} Draw",
			Density = "+{value} Density",
			Control = "+{value} Control",
			SentryDamage = "Sentry damage +{value}%",
			AegisRecharge = "Aegis re-forms {value}% faster",
			RelayCooldown = "Relay recasts {value}% sooner",
			CritDamage = "+{value}% critical damage",
			ExecuteDamage = "+{value}% damage to foes below 35% health",
			RiposteDamage = "+{value}% riposte and finisher damage",
			BlockCost = "Blocking costs {value}% less stamina",
			GuardPosture = "Lose {value}% less posture while blocking",
			DodgeCost = "Dodging costs {value}% less stamina",
			Threat = "+{value}% threat from your damage",
			SpellDamage = "+{value}% spell damage",
			SpellArea = "+{value}% spell area",
			ReactionDamage = "+{value}% Reaction damage",
			OverflowDuration = "Overflow lasts {value} s longer",
			BeaconSlots = "+{value} Beacon slot",
			HealPower = "+{value}% healing from your skills",
			MoveSpeed = "+{value}% movement speed",
			LootLuck = "+{value}% chance of gear drops",
			GoldFind = "+{value}% gold from foes",
			MarkPower = "+{value}% damage from your Marks",
			AbilityPower = "+{value}% ability damage",
			AbilityCooldown = "Abilities recover {value}% faster",
		} :: { [string]: string },
		ParryFrames = "Parry window +{value} frames",

		Uniques = {
			Undertow = { Name = "Undertow", Description = "Every 4th hit on the same foe releases a tidal burst for 40% of your weapon damage around it." },
			Brineward = { Name = "Brineward", Description = "Dropping below 30% health raises a shield worth 25% of your max health. Once every 45 s." },
			RiptideReflex = { Name = "Riptide Reflex", Description = "Parries grant a Resonance stack and refill 10% of your Current." },
			Deepglass = { Name = "Deepglass", Description = "Spells cast above 80% Current deal 18% more damage." },
			Spireheart = { Name = "Spireheart", Description = "Resonance doesn't decay while you're above 60% health." },
			Lanternwake = { Name = "Lanternwake", Description = "A Perfect Dodge heals 8% of your max health." },
		} :: { [string]: { Name: string, Description: string } },

		-- Character sheet
		Sheet = {
			Stats = "Attributes",
			Base = "{value}",
			WithGear = "{base} + {gear}",
			Level = "Level {level}",
			Archetype = "{archetype}",
			PositionLine = "{position}",
			NoPosition = "No Position yet",
			PointsToSpend = "{points} points to spend",
			NoPointsToSpend = "No points to spend",
			Pending = "+{points}",
			ConfirmStats = "Confirm",
			ResetStats = "Reset",
			StatHint = "Next point: {effect}",
			SoftCapHint = "Past {threshold} points each point counts for {percent}%.",
			Derived = "Combat",
			Health = "Health",
			Stamina = "Stamina",
			Current = "Current",
			Armor = "Damage reduction",
			Crit = "Critical chance",
			WeaponDamage = "Weapon damage",
			Bonuses = "Bonuses (gear and skills)",
			NoBonuses = "No bonuses from gear or skills yet.",
			Effects = "Unique effects",
			Rotate = "Drag to rotate",
		},

		-- Quick items (Z / X)
		QuickEmpty = "Quick item: right-click a consumable and choose a quick slot.",

		Errors = {
			NotLoaded = "Your bag is still loading.",
			Invalid = "That can't be done.",
			Missing = "That item is gone.",
			Locked = "That item is locked.",
			Equipped = "Unequip it first.",
			Full = "Your bag is full.",
			BankFull = "Your storage is full.",
			Level = "Your level is too low.",
			WrongSlot = "That doesn't go there.",
			Funds = "You can't afford that.",
			Materials = "You're missing materials.",
			Unknown = "You haven't learned that recipe.",
			AlreadyKnown = "You already know everything this teaches.",
			Distance = "Move closer to the station.",
			Dead = "You can't do that while fallen.",
			Busy = "Finish what you're doing first.",
			Cooldown = "Not ready yet.",
			Maximum = "Already at the highest upgrade.",
			NotDamaged = "Nothing to repair.",
			CantSell = "Shops won't buy that.",
			Healthy = "Already full.",
			TradeLocked = "Finish your trade first.",
			NeedAttunement = "Attune at the Shrine before slotting a Beacon core.",
			WrongStation = "This station can't do that.",
			Cancelled = "Crafting interrupted.",
		} :: { [string]: string },
	},

	-- Crafting stations, shops and the bank.
	Stations = {
		Names = {
			Forge = "Forge",
			Armorer = "Armorer's Bench",
			Alchemy = "Alchemy Table",
			Loom = "Current Loom",
			Altar = "Altar",
			Shop = "Harbor Provisions",
			TokenShop = "Token Exchange",
			Bank = "Climbers' Vault",
			Positions = "Hall of Positions",
		} :: { [string]: string },
		Open = "Use",
		TabCraft = "Craft",
		TabUpgrade = "Upgrade",
		TabRepair = "Repair",
		TabSalvage = "Salvage",
		TabBuy = "Buy",
		TabSell = "Sell",
		TabBuyback = "Buy back",
		TabDeposit = "Store",
		TabWithdraw = "Withdraw",
		Recipes = "Known recipes",
		NoRecipes = "No recipes known here yet. Pick up new materials, buy blueprints or finish quests to learn more.",
		Materials = "Materials",
		Have = "{have} / {need}",
		Fee = "Fee {gold} gold",
		Craft = "Craft",
		CraftCount = "Craft x{count}",
		Crafting = "Crafting...",
		Crafted = "Crafted {name}",
		Track = "Track",
		Tracking = "Tracking",
		UpgradeTo = "Upgrade to +{level}",
		Chance = "{chance}% success",
		NextDamage = "Damage {from}  ->  <font color=\"#6EE07A\">{to}</font>",
		NextArmor = "Armor {from}%  ->  <font color=\"#6EE07A\">{to}%</font>",
		FailNote = "From +7, an attempt can fail: the item is kept at its level, the gold and materials are spent.",
		UpgradeSuccess = "{name} is now +{level}!",
		UpgradeFailed = "The upgrade failed. {name} stays at +{level}.",
		RepairFor = "Repair for {gold} gold",
		RepairAll = "Repair all ({gold} gold)",
		Repaired = "Repaired",
		SalvageFor = "Salvage into {yield}",
		Salvaged = "Salvaged into {yield}",
		Price = "{price}",
		Buy = "Buy",
		BuyCount = "Buy x{count}",
		Sell = "Sell",
		SellFor = "Sell for {gold} gold",
		Sold = "Sold for {gold} gold",
		Bought = "Bought {name}",
		BuybackEmpty = "Items you sell appear here for a while, in case you change your mind.",
		NothingHere = "Nothing to show here.",
		Stored = "Stored",
		Withdrawn = "Withdrawn",
		VaultSlots = "Vault {used} / {max}",
		ConfirmSellTitle = "Sell this item?",
		ConfirmSell = "Sell {name} for {gold} gold? You can buy it back here for a while.",
		ConfirmSalvageTitle = "Salvage this item?",
		ConfirmSalvage = "Break {name} down into {yield}? This can't be undone.",
		ConfirmUpgradeTitle = "Risky upgrade",
		ConfirmUpgrade = "This attempt has a {chance}% chance to succeed. If it fails you keep {name} at +{level}, but the gold and materials are spent.",
		PriceCompare = "Your {name}: {value}",
	},

	Training = {
		TrainingDummy = "Training Dummy",
		SparringDummy = "Sparring Dummy",
	},

	-- Enemy names, keyed by mob id (Shared.Data.Mobs).
	Mobs = {
		Bilgecrab = "Bilgecrab",
		DrownedSailor = "Drowned Sailor",
		MarshWisp = "Marsh Wisp",
		LanternAcolyte = "Lantern Acolyte",
		RustwoodStalker = "Rustwood Stalker",
		CisternLeech = "Cistern Leech",
		Brinehulk = "Brinehulk",
		Brinewarden = "The Brinewarden",
	} :: { [string]: string },

	-- Phase 11: quest, achievement, dialogue and map interface labels. Quest, NPC, achievement and
	-- tutorial content lives in Strings.Quests / Npcs / Achievements / Tutorial.
	QuestUI = {
		LogTitle = "Quest Log",
		Tabs = {
			Main = "Main Story",
			Side = "Side Quests",
			Daily = "Dailies",
			Weekly = "Weeklies",
			Achievements = "Achievements",
		} :: { [string]: string },
		Empty = "Nothing here yet. Speak with the people of Lowharbor.",
		Objectives = "Objectives",
		Rewards = "Rewards",
		RewardXP = "{xp} XP",
		RewardGold = "{gold} Gold",
		RewardShards = "{shards} Spire Shards",
		Level = "Recommended level {level}",
		Track = "Track",
		Untrack = "Untrack",
		Abandon = "Abandon",
		AbandonConfirm = "Abandon {name}? Progress will be lost.",
		Reroll = "Reroll",
		RerollsLeft = "{count} rerolls left today",
		ResetsIn = "Resets in {time}",
		Progress = "{done}/{total}",
		Distance = "{distance} studs",
		Ready = "Ready to turn in",
		ReturnTo = "Return to {name}",
		Completed = "Completed",
		Accepted = "New quest: {name}",
		QuestComplete = "Quest complete: {name}",
		ObjectiveDone = "{objective}",
		Collapse = "Hide",
		Expand = "Quests",
		-- Dialogue box
		Accept = "Accept",
		Decline = "Not now",
		TurnIn = "Hand in",
		Goodbye = "Farewell",
		Continue = "Continue",
		Talk = "Talk",
		AboutQuest = "About {name}",
		-- Achievements
		AchievementUnlocked = "Achievement unlocked",
		TitleUnlocked = "New title: {title}",
		TitleNone = "No title",
		TitlePick = "Title",
		Hidden = "Hidden achievement",
		-- Map
		MapTitle = "Map",
		MapLegend = "Legend",
		MapWaystone = "Waystone",
		MapTravel = "Travel here",
		MapTravelHint = "Stand at a Waystone to travel",
		TravelArrived = "You step out of the Current at {name}.",
		TravelErrors = {
			NotAtWaystone = "Stand at a Waystone to travel.",
			Unknown = "You haven't attuned to that Waystone yet.",
			Cooldown = "The Current is still settling. Try again shortly.",
			Combat = "You can't travel while the Current is turbulent.",
			Busy = "You can't travel right now.",
		} :: { [string]: string },
		MapPinAdd = "Place pin",
		MapPinRemove = "Remove pin",
		MapFloor = "Floor {floor}: {name}",
		MapYou = "You",
		MapUnexplored = "Unexplored",
		-- Phase 11 client UI (QuestController, DialogueController, AchievementController, MapController)
		InProgress = "In progress",
		Tracked = "Tracked",
		NoneTracked = "No quest tracked",
		ResetDays = "{days}d {hours}h",
		ChoiceReady = "{name} (ready)",
		ChoiceProgress = "{name} (in progress)",
		RewardItem = "{name} x{count}",
		AchievementsSummary = "{done} / {total} unlocked",
		AchievementReward = "+{shards} Spire Shards",
		TitleReward = "Title: {title}",
		Unlocked = "Unlocked",
		MapTravelTo = "Travel to {name}?",
		MapNotDiscovered = "Not yet discovered",
		MapHere = "You are here",
		MapFloorLocked = "Not yet reached",
		MapNoData = "No map of this floor yet",
		MapPinsFull = "You can place {count} pins on a floor.",
		MapQuest = "Quest objective",
		MapPin = "Pin",
		MapRecenter = "Centre on me",
		MapControlsMouse = "Drag to pan  ·  Wheel to zoom  ·  Right-click to place a pin",
		MapControlsTouch = "Drag to pan  ·  Pinch to zoom  ·  Hold to place a pin",
		MapControlsGamepad = "Left stick: pan  ·  Right stick: zoom  ·  A: select  ·  X: pin  ·  LB / RB: floor",
		MapDiscovered = "Discovered",
		MapAvailable = "Has a task for you",
		MapOpenQuest = "Open in Quest Log",
		MapZoomIn = "Zoom in",
		MapZoomOut = "Zoom out",
		MapPrevFloor = "Previous floor",
		MapNextFloor = "Next floor",
		DialogueSkipMouse = "Click to continue",
		DialogueSkipTouch = "Tap to continue",
		DialogueSkipGamepad = "Press A to continue",
		PlateLevel = "Lv {level}",
		Errors = {
			TooFar = "Come closer to speak with them.",
			NotAvailable = "That quest isn't available.",
			NotReady = "The task isn't finished yet.",
			LogFull = "Your quest log is full.",
			NoRerolls = "No rerolls left today.",
			BagFull = "Your bag is full. Make room, then hand it in.",
		} :: { [string]: string },
	},

	-- Phase 11: the docks tutorial (TutorialService, TutorialController). Prompts stay at six
	-- words or fewer; {key} is the bound key or button for the current device.
	Tutorial = {
		Welcome = "Welcome to Lowharbor, Climber.",
		Prompts = {
			Move = "Walk to the lantern",
			Sprint = "Hold {key} to sprint",
			SprintTouch = "Push the stick fully to sprint",
			Combo = "Strike the crab",
			Dodge = "Dodge the sailor's swing",
			Parry = "Block just as it strikes",
			Spell = "Cast Tide Bolt",
			Resonance = "Land hits to build Resonance",
			Finish = "Defeat the Drowned Sailor",
		} :: { [string]: string },
		Glyphs = {
			MoveKeys = "W A S D",
			MoveStick = "Left Stick",
			MoveTouch = "Thumbstick",
		} :: { [string]: string },
		Count = "{done}/{total}",
		Tutor = "Old Pell",
		Callouts = {
			Combo = "Go on, give it a few whacks!",
			DodgeWatch = "Here it comes. Roll clear!",
			ParryWatch = "Steady... wait for it...",
			ParryNow = "Now! Block as the blade falls!",
			ParryGood = "Ha! That's the way!",
			Spell = "Feel the tide? Let it fly!",
			Finish = "He's tiring. Finish him!",
		} :: { [string]: string },
		ResonanceTitle = "Resonance!",
		ResonanceBody = "Hits and spells build it. At 5 stacks, unleash a Confluence.",
		Continue = "Continue",
		Skip = "Skip tutorial",
		FinishedTitle = "Ready to climb",
		Finished = "Tutorial complete. Brannoc waits on the quay.",
		Skipped = "Tutorial skipped. Brannoc waits on the quay.",
	},

	-- Phase 10: Floor Guardians (GuardianService, GuardianController).
	Guardians = {
		Names = {
			Brinewarden = "The Brinewarden",
		} :: { [string]: string },
		Subtitles = {
			Brinewarden = "Keeper of the First Gate",
		} :: { [string]: string },
		-- Phase cards, per Guardian and phase number.
		Phases = {
			Brinewarden = {
				"The Warden's Vigil",
				"The Rising Tide",
				"The Shell Breaks",
			},
		} :: { [string]: { string } },
		PhaseHints = {
			Brinewarden = {
				"Strike the seam in its shell, at its back.",
				"Cast while the tide is high. Strike while it ebbs.",
				"Its core is exposed. Dodge through the wave.",
			},
		} :: { [string]: { string } },
		Floors = {
			["1"] = "Lowharbor",
			["2"] = "Amberveil",
			["3"] = "Glasswater",
			["4"] = "Ironroot",
			["5"] = "The Drowned Court",
		} :: { [string]: string },

		Prompt = "Challenge the Brinewarden",
		PromptObject = "The First Gate",
		Gathering = "The Gate stirs. Climbers at the Gate join you in {seconds}s ({count}/{max})",
		Joined = "You stand with {count} Climbers before the Gate",
		ArenaBusy = "The Gate cannot open right now. Try again in a moment.",
		GatheringFull = "The Gate already holds {max} Climbers. Wait for the next challenge.",
		BelowLevel = "The Brinewarden is level {level}. Prepare well, Climber.",
		SkipIntro = "Press {key} to skip",
		SkipIntroTouch = "Tap to skip",

		BossLevel = "Lv {level}",
		Tide = {
			Calm = "Calm Water",
			High = "High Tide",
			Ebb = "Ebb Tide",
		} :: { [string]: string },
		TideHint = {
			High = "Pressure 5: spells surge",
			Ebb = "Pressure 1: the shell dries, strike it",
		} :: { [string]: string },
		TideTurning = "The tide turns...",
		Grabbed = "Seized! Allies: strike the Warden to break its grip",

		Victory = "Guardian Felled",
		VictoryTime = "{time}",
		VictoryParty = "With {names}",
		VictorySolo = "Alone",
		Unlocked = "Floor {floor}: {name} unlocked",
		FirstClear = "First clear: +{shards} Spire Shards, +{points} skill points",
		Wipe = "The tide recedes...",
		WipeHint = "The Brinewarden waits at the First Gate.",
		BannerServer = "Floor {floor} has been cleared by {names}!",
		BannerGlobal = "Across the Spire: Floor {floor} cleared by {names}",
		NextFloorClosed = "The stair beyond the Gate is still sealed to you.",
		NextFloorPending = "The way to {name} lies open. Its stair will rise soon.",
	},

	MobUI = {
		Nameplate = "Lv {level}  {name}",
		EliteNameplate = "Lv {level}  Elite {name}",
	},

	Waystones = {
		F1_ClimbersRest = "Climbers' Rest",
		F1_TidewatchSteps = "Tidewatch Steps",
		F1_ReedwardenPost = "Reedwarden Post",
		F1_RustwoodCamp = "Rustwood Camp",
		F1_CisternMouth = "Cistern Mouth",
		F1_GateApproach = "Gate Approach",
	} :: { [string]: string },

	-- Phase 9: hidden areas (SecretService) and region names.
	Secrets = {
		F1_SmugglersCove = "Smugglers' Cove",
		F1_ForestHollow = "The Hollow Under Rustwood",
		F1_ReedShrine = "Shrine of the Drowned Reed",
		F1_CliffShrine = "Windward Cliff Shrine",
	} :: { [string]: string },
	Regions = {
		Town = "Lowharbor",
		Harbour = "Lowharbor Bay",
		OldWharf = "The Old Wharf",
		TidepoolMarsh = "Tidepool Marsh",
		RustwoodForest = "Rustwood Forest",
		Downs = "Gatewatch Downs",
		Cistern = "The Sunken Cistern",
		FirstGate = "The First Gate",
	} :: { [string]: string },

	-- Phase 11: quests, NPCs and achievements (Data/Quests, Data/Npcs, Data/Achievements).
	Quests = {
		-- MAIN STORY ---------------------------------------------------------------------------
		F1_M01 = {
			Name = "Salt in the Lungs",
			Summary = "You woke on the Lowharbor quay. The Dockmaster wants a word.",
			Objectives = { "Speak with Brannoc Hale on the quay" },
			Offer = {
				"Easy, easy. Cough it up. The sea does that to all who wash in.",
				"You came up from below, didn't you? Another Climber, then.",
				"Talk to me when you can stand straight.",
			},
			Progress = { "Come on over. Don't make an old man shout across the quay." },
			Complete = {
				"There. Colour's back in your face. This is Lowharbor, first of the Spire's floors.",
				"Every Climber starts on this quay. Few finish the Climb. Go see Warden Ysolde at the Guild.",
			},
		},
		F1_M02 = {
			Name = "A Climber's Mark",
			Summary = "Brannoc sends you to the Climbers' Guild to be marked.",
			Objectives = { "Climb to the Guild steps", "Speak with Warden Ysolde" },
			Offer = {
				"No mark, no Climb. That's the Guild's rule, and it's a fair one.",
				"Up the avenue to the Guild steps. Ysolde Tarn keeps the register.",
			},
			Progress = { "The Guild is at the top of the Climb. Follow the lamps." },
			Complete = {
				"Another name for the register. Hold still while I set the mark.",
				"The Spire counts its Climbers, and what it counts, it remembers. Do not make it regret you.",
			},
		},
		F1_M03 = {
			Name = "Rest at the Stone",
			Summary = "Waystones are the Climber's lifeline. Find two.",
			Objectives = { "Discover 2 Waystones" },
			Offer = {
				"Waystones hold the Current steady. Touch one and the Spire remembers where you stood.",
				"Find two. Tidewatch Steps and the Climbers' Rest are the nearest.",
			},
			Progress = { "Two stones. Touch them and feel the hum." },
			Complete = {
				"You felt it, then. The Current in the stone.",
				"Die near a Waystone and you wake beside it. Never forget where the last one is.",
			},
		},
		F1_M04 = {
			Name = "Teeth of the Tide",
			Summary = "Bilgecrabs infest the old wharf. Thin them out.",
			Objectives = { "Slay Bilgecrabs near the Old Wharf" },
			Offer = {
				"Bilgecrabs have swarmed the wharf shallows. They cut nets, boots and ankles.",
				"Cull six. Watch for the claw before it falls, and strike when it recovers.",
			},
			Progress = { "The crabs haven't gone anywhere. Six, Climber." },
			Complete = {
				"Six shells. Good. The harbor can breathe a little easier.",
				"Their shells make decent armour, if you know a good Armorer.",
			},
		},
		F1_M05 = {
			Name = "The Shrine of Currents",
			Summary = "Attune to the Current at the Shrine in the Rotunda.",
			Objectives = { "Attune at the Shrine of Currents" },
			Offer = {
				"Steel will carry you far. The Current carries you farther.",
				"The Shrine in the Rotunda will attune you. Choose well. It shapes how you fight.",
			},
			Progress = { "The Shrine is in the Rotunda. Touch it and choose." },
			Complete = {
				"I can see it in you now. The Current answers your hand.",
				"Take this blade. It carries the old tide-forging. Use steel and spell together.",
			},
		},
		F1_M06 = {
			Name = "Lights in the Reeds",
			Summary = "Wisps drift over Tidepool Marsh. The Reedwarden wants them gone.",
			Objectives = { "Reach the Reedwarden Post", "Slay Marsh Wisps" },
			Offer = {
				"The marsh is lit at night, and not by any friend. Wisps lure the weary into the black water.",
				"Reedwarden Osk keeps the post. Go to him. He will tell you how to put the lights out.",
			},
			Progress = { "The reeds are quiet. Too quiet. Four wisps, Climber." },
			Complete = {
				"Wisps are lost souls bound to the Current. Don't pity them, not in the reeds.",
				"Four fewer lamps tonight. Take this and keep to the boardwalks.",
			},
		},
		F1_M07 = {
			Name = "What the Sailors Took",
			Summary = "Drowned sailors haunt the Old Wharf, clutching what they stole.",
			Objectives = { "Reach the Old Wharf", "Slay Drowned Sailors" },
			Offer = {
				"Drowned men keep walking the Old Wharf, as if the ships still sailed.",
				"They hoard what the tide gave them. Go and put them to rest. Bring back what's the Watch's.",
			},
			Progress = { "The wharf's still full of them. Five, Climber." },
			Complete = {
				"They were crew of the first ships to reach the Spire, so the old rolls say.",
				"The sea took them, the Spire kept them. Take your pay, you've earned it.",
			},
		},
		F1_M08 = {
			Name = "Hunters in Rustwood",
			Summary = "Rustwood Stalkers have turned the forester's camp into a siege.",
			Objectives = { "Discover the Rustwood Camp", "Slay Rustwood Stalkers" },
			Offer = {
				"Stalkers have the forest. Hesk Thornwell holds the camp, barely.",
				"Reach him. Then help him clear the trees.",
			},
			Progress = { "Hesk is waiting. Rustwood doesn't forgive hesitation." },
			Complete = {
				"Hmph. Five down. The wood sounds different.",
				"Rust goes into the bark, the bark into the wolves. The Spire changes all it touches.",
			},
		},
		F1_M09 = {
			Name = "The Lagoon's Lord",
			Summary = "A Brinehulk lurks in the lagoon. Strike its exposed back.",
			Objectives = { "Slay the Brinehulk in the lagoon" },
			Offer = {
				"A Brinehulk has taken the lagoon. It will not fall to a front charge.",
				"Strike its back, where the shell is thin. Parry the slam, then circle.",
			},
			Progress = { "The lagoon is waiting. Circle it. Strike from behind." },
			Complete = {
				"The Brinehulk is down. You do well, Climber.",
				"Few thought a fresh Climber could fell one. Now there is another door to open. Go see Ilse.",
			},
		},
		F1_M10 = {
			Name = "Beneath the Pumphouse",
			Summary = "The Archivist's records point to the Sunken Cistern.",
			Objectives = { "Speak with Ilse Marrow", "Clear the Sunken Cistern" },
			Offer = {
				"Every Floor has a Keeper. Ours is the Brinewarden, and he guards the First Gate.",
				"Records say the Warden's seal lies in the Sunken Cistern, under the old pumphouse.",
				"Go below. Bring back what you find.",
			},
			Progress = { "The Cistern is waiting. Bring friends if you can." },
			Complete = {
				"The seal was there. And these scratches, a Climber's, not the Warden's.",
				"Someone reached the Gate before you, and did not return. Take this and be careful.",
			},
		},
		F1_M11 = {
			Name = "The Keeper's Price",
			Summary = "Ysolde warns you of the Gate and what its Keeper demands.",
			Objectives = { "Speak with Warden Ysolde", "Discover the Gate Approach" },
			Offer = {
				"The Brinewarden does not die. It waits. Every Climber who reached the Gate paid with blood.",
				"Go to the Gate Approach. See it for yourself, then come back to me.",
			},
			Progress = { "The Approach is above the Downs. Take care." },
			Complete = {
				"You saw it. The Gate is real, and so is its Keeper.",
				"I will not lie to you: many fell there. But you are ready. Strike when the moment is right.",
			},
		},
		F1_M12 = {
			Name = "The First Gate",
			Summary = "Defeat the Brinewarden and open the way up the Spire.",
			Objectives = { "Defeat the Brinewarden" },
			Offer = {
				"The Gate is yours to open. Fell the Brinewarden and the Spire's next Floor opens to you.",
				"May the Current carry you.",
			},
			Progress = { "The Gate is waiting. So is the Keeper." },
			Complete = {
				"The First Gate stands open. A Climber has passed it at last.",
				"Floor 2 awaits. But remember, Lowharbor, and the people who kept the lamps lit.",
			},
		},

		-- SIDE QUESTS --------------------------------------------------------------------------
		F1_S01 = {
			Name = "Nets and Knots",
			Summary = "Brannoc needs marsh fibre to rig the quay's torn nets.",
			Objectives = { "Gather Marsh Fibre" },
			Offer = {
				"My nets are rags. Bring me eight bundles of marsh fibre and I'll see you right.",
				"Cut it from the reeds. Mind the wisps.",
			},
			Progress = { "Eight bundles of fibre. The reeds are plenty, if you're patient." },
			Complete = {
				"Good stuff. The nets will hold again.",
				"Here, a pair of gloves. They held up better than my nets did.",
			},
		},
		F1_S02 = {
			Name = "What the Tide Brings",
			Summary = "Old Pell wants shells and scrap from the shore.",
			Objectives = { "Gather Brine Shells", "Gather Iron Scrap" },
			Offer = {
				"Aye, the tide brings all sorts. Shell for my needles, scrap for the weights.",
				"Bring me both, and I'll pay in something shinier than coin.",
			},
			Progress = { "Shells and scrap. Not much to ask of a Climber." },
			Complete = {
				"That'll do nicely. These came out of the same tide, years ago.",
				"Funny. The sea gives back what it likes, just not who.",
			},
		},
		F1_S03 = {
			Name = "The Floors Above",
			Summary = "Ilse wants proof that secret places remain on Floor 1.",
			Objectives = { "Find the hidden Smugglers' Cove", "Find the Shrine of the Drowned Reed" },
			Offer = {
				"The records speak of hidden places. A smugglers' cove, and a shrine in the reeds.",
				"If they exist, they will tell us how the Floors above were built.",
			},
			Progress = { "A cove and a shrine. The records say they exist." },
			Complete = {
				"Both are real. The Floors are older than the Guild thinks.",
				"Each tier is a shell around the last. Keep this. You've earned it.",
			},
		},
		F1_S04 = {
			Name = "Brine Pearls",
			Summary = "Tobin Quill pays well for tide pearls.",
			Objectives = { "Gather Tide Pearls" },
			Offer = {
				"Tide pearls! Customers beg me for them, and I have none. Bring me three.",
				"Sailors and stalkers sometimes carry them. Don't ask where they found them.",
			},
			Progress = { "Three pearls. Think of the profit, my friend." },
			Complete = {
				"Beautiful. Hold one up to the light and you can see the Current inside.",
				"A fair price, and a trinket for your trouble.",
			},
		},
		F1_S05 = {
			Name = "Candles for the Drowned",
			Summary = "Sister Caddith wants wisp light for the drowned's candles.",
			Objectives = { "Gather Wisp Essence", "Carry the light to the Old Wharf" },
			Offer = {
				"The drowned wander because no light guides them home. I would light candles for them.",
				"Bring wisp essence, and carry the light to the Old Wharf.",
			},
			Progress = { "The wharf waits for its candles." },
			Complete = {
				"Thank you. The wharf is brighter tonight.",
				"The sea took them, but the Spire holds them. May they find rest.",
			},
		},
		F1_S06 = {
			Name = "Parry Drill",
			Summary = "Captain Maren drills you in the parry.",
			Objectives = { "Parry enemy strikes" },
			Offer = {
				"Parry is the Watch's oldest lesson. Ten clean parries, soldier.",
				"Block the instant the blow lands. Early or late, you eat steel.",
			},
			Progress = { "Ten parries. Keep at it." },
			Complete = {
				"Better. Your timing improves.",
				"Take this charm. The Watch gives it to those who learn.",
			},
		},
		F1_S07 = {
			Name = "The Watch Needs Steel",
			Summary = "The Watch's stores are empty. Forge a blade.",
			Objectives = { "Forge a Lanternedge Arcblade" },
			Offer = {
				"The Watch's armoury is bare. Forge a Lanternedge Arcblade. Scrap, rustwood and wisp essence.",
				"Bring it to me when done.",
			},
			Progress = { "A blade, soldier. The forge is open." },
			Complete = {
				"Fine work. It will serve.",
				"Take this and keep the forge hot.",
			},
		},
		F1_S08 = {
			Name = "Lanterns in the Reeds",
			Summary = "Lantern Acolytes lurk by the Reedwarden Post.",
			Objectives = { "Slay Lantern Acolytes" },
			Offer = {
				"Acolytes in lamp-robes wander the marsh. They worship the lights.",
				"Put five down. They don't listen.",
			},
			Progress = { "The lamps are lit. Five acolytes." },
			Complete = {
				"Quiet again. Thank you.",
				"They were Climbers once, I think. The Current took them.",
			},
		},
		F1_S09 = {
			Name = "Rust on the Bark",
			Summary = "Hesk wants the stalkers culled and fresh rustwood cut.",
			Objectives = { "Slay Rustwood Stalkers", "Gather Rustwood" },
			Offer = {
				"Stalkers again, and the bark's gone bad. Kill four. Cut eight lengths of rustwood.",
				"Fresh wood or none.",
			},
			Progress = { "Four stalkers, eight lengths. I'll wait." },
			Complete = {
				"Good wood. Strong.",
				"Take these. A forester's thanks.",
			},
		},
		F1_S10 = {
			Name = "Fish That Glow",
			Summary = "Fen dares you to follow the glowing fish through the canals.",
			Objectives = { "Reach the North Canal Falls", "Reach the South Canal Falls", "Reach the Canal Mouth" },
			Offer = {
				"Psst. Glowing fish! In the canals, where the Current pours down.",
				"Follow them. North falls, south falls, then the mouth. Bet you can't.",
			},
			Progress = { "Not done yet? The fish are getting away." },
			Complete = {
				"You saw them! The Current makes them glow.",
				"Here, your share. Don't tell the Watch.",
			},
		},

		-- DAILIES AND WEEKLIES (no dialogue) ------------------------------------------------------
		F1_DK01 = { Name = "Crab Cull", Summary = "Thin the Bilgecrabs along the shore.", Objectives = { "Slay Bilgecrabs" } },
		F1_DK02 = { Name = "Wharf Watch", Summary = "Put drowned sailors back to rest.", Objectives = { "Slay Drowned Sailors" } },
		F1_DK03 = { Name = "Snuffing the Lights", Summary = "Put out the marsh wisps.", Objectives = { "Slay Marsh Wisps" } },
		F1_DK04 = { Name = "Forest Patrol", Summary = "Keep Rustwood's stalkers at bay.", Objectives = { "Slay Rustwood Stalkers" } },
		F1_DG01 = { Name = "Scrap Run", Summary = "Gather iron scrap for the smiths.", Objectives = { "Gather Iron Scrap" } },
		F1_DG02 = { Name = "Fibre Bundles", Summary = "Cut marsh fibre for the weavers.", Objectives = { "Gather Marsh Fibre" } },
		F1_DG03 = { Name = "Wisp Light", Summary = "Collect essence for the Cathedral's lamps.", Objectives = { "Gather Wisp Essence" } },
		F1_DG04 = { Name = "Timber Order", Summary = "Cut rustwood for the camp's carpenters.", Objectives = { "Gather Rustwood" } },
		F1_DD01 = { Name = "Down the Cistern", Summary = "Clear the Sunken Cistern once.", Objectives = { "Clear the Sunken Cistern" } },
		F1_DD02 = { Name = "Leech Hunt", Summary = "Thin the Cistern Leeches.", Objectives = { "Slay Cistern Leeches" } },
		F1_DD03 = { Name = "Cistern Twice", Summary = "Clear the Sunken Cistern twice.", Objectives = { "Clear the Sunken Cistern" } },
		F1_W01 = { Name = "Weekly Cull", Summary = "Keep Floor 1 safe. Slay sixty enemies.", Objectives = { "Slay enemies" } },
		F1_W02 = { Name = "Cistern Regular", Summary = "Delve the Sunken Cistern five times.", Objectives = { "Clear the Sunken Cistern" } },
		F1_W03 = { Name = "Warden's Toll", Summary = "Fell the Brinewarden once this week.", Objectives = { "Defeat the Brinewarden" } },
		F1_W04 = { Name = "Drill and Discipline", Summary = "Parry and unleash Confluences.", Objectives = { "Parry enemy strikes", "Unleash Confluences" } },
	} :: { [string]: { Name: string, Summary: string, Objectives: { string }, Offer: { string }?, Progress: { string }?, Complete: { string }? } },

	Npcs = {
		Brannoc = {
			Name = "Brannoc Hale",
			Role = "Dockmaster",
			Greetings = { "Mind the quay, it's slick tonight.", "Another Climber. The sea keeps sending them." },
			Idle = { "Ropes don't tie themselves.", "I've watched that lighthouse all my life." },
		},
		Ysolde = {
			Name = "Ysolde Tarn",
			Role = "Warden of the Climbers' Guild",
			Greetings = { "Climber. State your business.", "The Guild is watching." },
			Idle = { "Stand tall. The Spire sees weakness.", "The Gate does not forgive hesitation." },
		},
		Pell = {
			Name = "Old Pell",
			Role = "Net-mender",
			Greetings = { "One eye's enough for this net, lad.", "Ah, fresh Climber. Sit and listen." },
			Idle = { "The tide's moods are older than I am.", "Knot by knot, lad." },
		},
		Ilse = {
			Name = "Ilse Marrow",
			Role = "Archivist of the Library of Floors",
			Greetings = { "Quietly, please. The records are old.", "Ah, a visitor. Rare." },
			Idle = { "Every Floor is a chapter.", "The ink never dries here." },
		},
		Tobin = {
			Name = "Tobin Quill",
			Role = "Provisioner",
			Greetings = { "Welcome, welcome! Best prices in Lowharbor!", "Supplies for the Climb?" },
			Idle = { "Never climb hungry.", "Coin's all well, but trade is better." },
		},
		Caddith = {
			Name = "Sister Caddith",
			Role = "Cathedral of the Ascent",
			Greetings = { "Peace be on you, Climber.", "The Cathedral is open to all." },
			Idle = { "We light the dark so the dark does not forget us.", "Pray, if you will." },
		},
		Maren = {
			Name = "Maren Dusk",
			Role = "Captain of the Watch",
			Greetings = { "State your rank.", "Watch is short of hands. Climbers will do." },
			Idle = { "Eyes up. Shield up.", "Discipline keeps us alive." },
		},
		Osk = {
			Name = "Reedwarden Osk",
			Role = "Warden of the Marsh",
			Greetings = { "Stay on the boards.", "You smell of the harbor. Be careful." },
			Idle = { "Marsh listens. Speak low.", "Lights in the reeds. Never follow them." },
		},
		Hesk = {
			Name = "Hesk Thornwell",
			Role = "Forester",
			Greetings = { "Quiet. Something's moving.", "Not many come this far." },
			Idle = { "Wood remembers.", "Rust in the bark. Rust in the blood." },
		},
		Fen = {
			Name = "Fen",
			Role = "Canal urchin",
			Greetings = { "Hey! Wanna see something neat?", "Psst. Climber. Over here." },
			Idle = { "Fish glow, y'know.", "Bridge is mine. Mostly." },
		},
	} :: { [string]: { Name: string, Role: string, Greetings: { string }, Idle: { string } } },

	Achievements = {
		List = {
			FirstBlood = { Name = "First Blood", Description = "Defeat your first enemy." },
			CrabCracker = { Name = "Crab Cracker", Description = "Defeat 25 Bilgecrabs." },
			SailorsRest = { Name = "Sailor's Rest", Description = "Put 25 Drowned Sailors to rest." },
			WispSnuffer = { Name = "Wisp Snuffer", Description = "Snuff out 25 Marsh Wisps." },
			ParryMaster = { Name = "Parry Master", Description = "Land 100 parries." },
			Untouchable = { Name = "Untouchable", Description = "Perfectly dodge 25 attacks." },
			Confluent = { Name = "Confluent", Description = "Unleash your first Confluence." },
			WaystoneWanderer = { Name = "Waystone Wanderer", Description = "Discover 6 Waystones or secrets." },
			CisternDelver = { Name = "Cistern Delver", Description = "Clear the Sunken Cistern." },
			CisternRegular = { Name = "Cistern Regular", Description = "Clear the Sunken Cistern 10 times." },
			Floor1Pioneer = { Name = "Floor 1 Pioneer", Description = "Defeat the Brinewarden." },
			WardenBreaker = { Name = "Warden Breaker", Description = "Defeat the Brinewarden 5 times." },
			Level5 = { Name = "Settling In", Description = "Reach level 5." },
			Level10 = { Name = "Climbing Steady", Description = "Reach level 10." },
			Level12 = { Name = "Ready for the Gate", Description = "Reach level 12." },
			TheFirstGateOpens = { Name = "The First Gate Opens", Description = "Complete the Floor 1 story." },
			Questing = { Name = "Questing", Description = "Complete 20 quests." },
			Crafter = { Name = "Crafter", Description = "Craft 10 items." },
			Tidepurse = { Name = "Tidepurse", Description = "Earn 5,000 gold." },
			TideTaken = { Name = "Tide-Taken", Description = "Fall 10 times and rise again." },
			SmugglersFriend = { Name = "Smuggler's Friend", Description = "Find the hidden Smugglers' Cove." },
			HollowKeeper = { Name = "Hollow Keeper", Description = "Find the Hollow Under Rustwood." },
		} :: { [string]: { Name: string, Description: string } },
		Titles = {
			ParryMaster = "Parry Master",
			Untouchable = "Untouchable",
			Confluent = "Confluent",
			CisternRegular = "Cistern Regular",
			Floor1Pioneer = "Floor 1 Pioneer",
			WardenBreaker = "Warden Breaker",
		} :: { [string]: string },
	},

	-- Phase 8: progression, Positions, the skill tree and abilities.
	Progression = {
		XPTooltip = "{xp} / {next} XP to level {level}",
		Archetypes = {
			Bladecaller = "Bladecaller",
			Currentweaver = "Currentweaver",
			Warden = "Warden",
			Stormrunner = "Stormrunner",
			Depthbreaker = "Depthbreaker",
		} :: { [string]: string },
		-- What one more point of each stat gives (Character sheet hints).
		StatEffects = {
			Vitality = "+{health} health, more damage reduction",
			Endurance = "+{stamina} stamina, faster recovery, more carry weight",
			Strength = "More Greatblade, Longsword and Spire Lance damage; more posture damage",
			Finesse = "More Twinfangs, Needle and Arcblade damage; crit chance and attack speed",
			Draw = "+{vessel} Current, faster regeneration, stronger Siphon",
			Density = "More spell damage, stronger shields and spell posture damage",
			Control = "Faster casting, wider spells, cheaper spells, Beacon slots at 20 / 40 / 60",
		} :: { [string]: string },
		Reasons = {
			Invalid = "That can't be done.",
			Points = "Not enough points.",
			Level = "Reach level {level} first.",
			NoPosition = "Choose a Position at the Hall of Positions first.",
			AlreadyChosen = "You already hold a Position. Respec to change it.",
			WrongPosition = "That belongs to another Position.",
			Taken = "Already learned.",
			Locked = "Learn a connected node first.",
			NotUnlocked = "Learn that ability in your skill tree first.",
			Funds = "You can't afford that.",
			Nothing = "Nothing to reset.",
			Distance = "Stand at the Hall of Positions to choose.",
			Combat = "Leave combat first.",
			NotLoaded = "Your progress is still loading.",
			Busy = "Finish what you're doing first.",
			Cooldown = "Not ready yet.",
			Current = "Not enough Current.",
			NoAbility = "No ability on your ability key. Equip one in the skill tree (N).",
		} :: { [string]: string },
	},

	Positions = {
		Title = "Skill Tree",
		HallTitle = "Hall of Positions",
		Names = {
			Vanguard = "Vanguard",
			Lancer = "Lancer",
			Tidecaller = "Tidecaller",
			Beaconkeeper = "Beaconkeeper",
			Pathfinder = "Pathfinder",
		} :: { [string]: string },
		Roles = {
			Vanguard = "Front line",
			Lancer = "Striker",
			Tidecaller = "Caster",
			Beaconkeeper = "Support",
			Pathfinder = "Scout",
		} :: { [string]: string },
		Blurbs = {
			Vanguard = "Hold the line. Taunt foes onto yourself, shrug off blows, answer every guard with a counter and shatter posture.",
			Lancer = "Strike first and finish fast. Chain critical hits, close any gap and execute foes on their last breath.",
			Tidecaller = "Bend the Current. Stronger and wider spells, longer Overflow and Reactions that hit like a wave.",
			Beaconkeeper = "Keep the climb alive. More and stronger Beacons, healing springs and lanterns that steady your allies.",
			Pathfinder = "Find the way. Move faster, lay traps, expose weak points and dig richer loot out of the Spire.",
		} :: { [string]: string },
		Branches = {
			Bulwark = "Bulwark",
			Challenge = "Challenge",
			Breaker = "Breaker",
			Edge = "Edge",
			Surge = "Surge",
			Reaper = "Reaper",
			Wellspring = "Wellspring",
			Maelstrom = "Maelstrom",
			Catalyst = "Catalyst",
			Lightkeeper = "Lightkeeper",
			Wellkeeper = "Wellkeeper",
			Lanternguard = "Lanternguard",
			Trailblazer = "Trailblazer",
			Snare = "Snare",
			Seeker = "Seeker",
		} :: { [string]: string },
		-- Notable and keystone node names.
		Nodes = {
			TidewallFrame = "Tidewall Frame",
			Unbowed = "Unbowed",
			BarnacleHide = "Barnacle Hide",
			LighthouseStance = "Lighthouse Stance",
			Bellwether = "Bellwether",
			IronLungs = "Iron Lungs",
			StandFirm = "Stand Firm",
			RallyingMast = "Rallying Mast",
			Counterweight = "Counterweight",
			Shatterguard = "Shatterguard",
			AnsweringBlow = "Answering Blow",
			Wreckmaker = "Wreckmaker",
			GlintEye = "Glint Eye",
			KeenEdge = "Keen Edge",
			Cascade = "Cascade",
			ThousandCuts = "Thousand Cuts",
			RiptideStep = "Riptide Step",
			Momentum = "Momentum",
			Slipstream = "Slipstream",
			WavebreakerCharge = "Wavebreaker Charge",
			LowTide = "Low Tide",
			Bloodwake = "Bloodwake",
			NoQuarter = "No Quarter",
			LastLight = "Last Light",
			DeepReservoir = "Deep Reservoir",
			Brimming = "Brimming",
			SpringTide = "Spring Tide",
			EndlessFlow = "Endless Flow",
			WideWaters = "Wide Waters",
			UndertowPull = "Undertow Pull",
			SwiftCurrents = "Swift Currents",
			EyeOfTheStorm = "Eye of the Storm",
			VolatileMix = "Volatile Mix",
			ChainReaction = "Chain Reaction",
			Saturate = "Saturate",
			GrandReaction = "Grand Reaction",
			SecondLamp = "Second Lamp",
			SteadyFlame = "Steady Flame",
			Watchfire = "Watchfire",
			Constellation = "Constellation",
			FreshSpring = "Fresh Spring",
			DeepwaterMend = "Deepwater Mend",
			SharedBreath = "Shared Breath",
			Wellmother = "Wellmother",
			WarmGlow = "Warm Glow",
			SteadfastLight = "Steadfast Light",
			BrightWard = "Bright Ward",
			BeaconOfTheClimb = "Beacon of the Climb",
			LightFeet = "Light Feet",
			SecondWind = "Second Wind",
			GhostTrail = "Ghost Trail",
			FarStrider = "Far Strider",
			BarbedWire = "Barbed Wire",
			QuickSet = "Quick Set",
			HuntersPatience = "Hunter's Patience",
			KillingGround = "Killing Ground",
			KeenNose = "Keen Nose",
			WeakSeam = "Weak Seam",
			TreasureSense = "Treasure Sense",
			SpireCartographer = "Spire Cartographer",
		} :: { [string]: string },
		Kinds = {
			Minor = "Minor node",
			Notable = "Notable",
			Active = "Ability",
			Keystone = "Keystone",
		} :: { [string]: string },
		Centre = "{position}",
		Points = "{points} skill points",
		Cost = "Cost: {cost}",
		Learn = "Learn",
		Learned = "Learned",
		NeedLink = "Learn a connected node first",
		NeedPoints = "Needs {cost} skill points",
		Equip = "Put on ability key",
		Equipped = "On ability key",
		Respec = "Respec",
		RespecFree = "Respec (free)",
		RespecCost = "Respec ({gold} gold)",
		RespecTitle = "Respec?",
		RespecBody = "Every stat point and skill point goes back to unspent so you can rebuild. Costs {gold} gold.",
		RespecBodyFree = "Every stat point and skill point goes back to unspent so you can rebuild. Your first respec is free.",
		RespecChange = "Also give up my Position (choose again at the Hall)",
		ChooseTitle = "Choose your Position",
		ChooseIntro = "Your Position is your role in a climbing party. It decides your skill tree and the abilities on your ability key. You can change it later with a respec.",
		ChooseLocked = "Positions open at level {level}.",
		ChooseHere = "Choose {name}",
		ChooseAway = "Choose at the Hall of Positions in Lowharbor",
		ChooseConfirmTitle = "Become a {name}?",
		ChooseConfirmBody = "You can change it later with a respec.",
		NoPositionYet = "You haven't chosen a Position yet.",
		NoPositionHint = "Reach level {level}, then visit the Hall of Positions in Lowharbor.",
		VisitHallHint = "Visit the Hall of Positions in Lowharbor to choose one.",
		ChooseHint = "Choose one of the five Positions. Each card lists its three abilities.",
		Abilities = "Abilities",
		AbilityStats = "{cost} Current  ·  {cooldown} s cooldown",
		Hint = "Drag or use the right stick to move · scroll or pinch to zoom",
		Recenter = "Show the whole tree",
		ZoomIn = "Zoom in",
		ZoomOut = "Zoom out",
		Details = "Select a node to see what it does.",
		DetailsTitle = "Details",
		Build = "Build",
		RadarHint = "Your attributes. Staged points show as a bright outline.",
		SkillPointsLabel = "Skill Points",
		StatPointsLabel = "Stat Points",
		LevelLabel = "Level",
		StateAvailable = "Ready to learn",
		NeedMorePoints = "Need {more} more skill points",
		Effects = "Effects",
		RequirementsTitle = "Requires",
		Requires = "Requires {names}",
		RequiresOne = "Requires one of: {names}",
		RequiresCore = "Grows straight from the Current core",
		AnyOneOf = "Any one of these is enough.",
		CostOne = "{cost} skill point",
		CostMany = "{cost} skill points",
		ClickToSelect = "Click to select",
		ClickToLearn = "Click again to learn",
		LearnedShort = "Learned",
		EquipShort = "Equip",
		RebuildTitle = "Rebuild",
	},

	Abilities = {
		Seawall = { Name = "Seawall", Description = "A wall of water shoves nearby foes back and shields you and allies within 18 studs for 25% of max health, with +12% armor, for 8 s." },
		HarborBell = { Name = "Harbor Bell", Description = "Toll a bell every foe within 22 studs must answer: they turn on you for 6 s. You gain +10% armor and lose 30% less posture blocking." },
		Keelbreaker = { Name = "Keelbreaker", Description = "Leap forward and split the ground: heavy posture damage around where you land, throwing light foes up." },
		Glintstorm = { Name = "Glintstorm", Description = "Four glinting cuts with +25% crit chance, then the edge leaps to up to three nearby foes." },
		RiptideLunge = { Name = "Riptide Lunge", Description = "Dash up to 18 studs, untouchable, cutting every foe along the way, then sweep where you land." },
		Severance = { Name = "Severance", Description = "One long severing thrust. Deals double damage to foes below 35% health." },
		Floodtide = { Name = "Floodtide", Description = "Drink from the Current: refill 35% of your Current and gain +20% spell damage and +15% cast speed for 10 s." },
		Maelstrom = { Name = "Maelstrom", Description = "Throw a vortex of your element: it drags foes together and grinds them for 4 s." },
		CatalystPulse = { Name = "Catalyst Pulse", Description = "A pulse soaks every foe within 12 studs in your element twice, then detonates on them." },
		Kindle = { Name = "Kindle", Description = "Your Beacons flare for 12 s: Sentries deal +50% damage, the Aegis re-forms 40% faster and the Relay recasts 30% sooner." },
		Tidewell = { Name = "Tidewell", Description = "Open a healing spring for 6 s: allies inside heal 4% of max health each second, foes inside take damage." },
		GuidingLantern = { Name = "Guiding Lantern", Description = "Heal yourself and allies within 30 studs for 18% of max health, with Renewing, +30% stamina regeneration and +8% armor for 10 s." },
		Windstep = { Name = "Windstep", Description = "Slip 20 studs forward, untouchable, then move 25% faster and dodge for 30% less stamina for 5 s." },
		Tanglewire = { Name = "Tanglewire", Description = "Throw a wire trap: for 8 s it roots and cuts every foe that stands in it." },
		ExposeWeakness = { Name = "Expose Weakness", Description = "A seeking bolt marks the foe it hits: your next blow within 10 s tears the seam open for heavy bonus damage." },
	} :: { [string]: { Name: string, Description: string } },

	Gallery = {
		Title = "UI Gallery",
		Subtitle = "Every component, rendered from UITheme. Studio only.",
		TabButtons = "Buttons",
		TabInputs = "Inputs",
		TabItems = "Items & Bars",
		TabFeedback = "Feedback",
		Primary = "Primary",
		Secondary = "Secondary",
		Danger = "Danger",
		Disabled = "Disabled",
		ToggleLabel = "Reduced Motion",
		SliderLabel = "Camera Shake",
		DropdownLabel = "Graphics Quality",
		KeybindLabel = "Dodge Roll",
		SearchLabel = "Filter items",
		ShowToast = "Show Toast",
		ShowConfirm = "Show Confirm",
		ShowModal = "Show Modal",
		ToastTitle = "Item Acquired",
		ToastBody = "Tidewrought Longsword",
		ConfirmTitle = "Salvage Item?",
		ConfirmBody = "Salvaging the Tidewrought Longsword returns 12 Brine Ore. This can't be undone.",
		ConfirmResultYes = "Confirmed",
		ConfirmResultNo = "Cancelled",
		ModalTitle = "Modal Window",
		ModalBody = "Modals dim and blur the world behind them and trap gamepad selection until closed.",
		HealthBar = "Health (damage trail)",
		CurrentBar = "Current (flowing)",
		StaminaBar = "Stamina",
		Damage = "Take Damage",
		Heal = "Heal",
		SlotTooltip = "Hover or select a slot to see its tooltip.",
		RarityNames = {
			Common = "Common",
			Uncommon = "Uncommon",
			Rare = "Rare",
			Epic = "Epic",
			Legendary = "Legendary",
			Mythic = "Mythic",
			SpireForged = "Spire-Forged",
		} :: { [string]: string },
		ScrollItem = "List row {index}",
	},
}

-- Replaces {name} placeholders with values from `args`.
function Strings.Format(template: string, args: { [string]: any }): string
	return (string.gsub(template, "{(%w+)}", function(key: string): string
		local value = args[key]
		if value == nil then
			return "{" .. key .. "}"
		end
		return tostring(value)
	end))
end

-- Friendly name for a binding string, e.g. "ButtonL2+ButtonR2" -> "LT + RT".
function Strings.KeyName(binding: string): string
	if binding == "" then
		return Strings.UI.Unbound
	end
	local parts = string.split(binding, "+")
	for index, part in parts do
		parts[index] = Strings.KeyNames[part] or part
	end
	return table.concat(parts, " + ")
end

return TableUtil.DeepFreeze(Strings)
