--!strict
-- Architectural styles used by BuildingPlanner. Each district picks a style;
-- a style decides materials, colours, window shapes, roof types and trim.

export type Style = {
	groundMaterial: string,
	groundColor: string,
	upperMaterial: string,
	upperColor: string,
	timberFrom: number?, -- first storey index (0-based) with half-timber overlay; nil = never
	corner: string, -- kit id for corners
	cornerMaterial: string?,
	floorMaterial: string,
	floorColor: string,
	groundFloorMaterial: string,
	roofMaterial: string,
	roofColors: { string },
	hipChance: number,
	archChance: number, -- chance a window panel is arched
	windowChance: number, -- side/back wall window density
	cornice: boolean,
	runeband: boolean,
	balconyChance: number,
	dormerChance: number,
	chimneyChance: number,
	bannerChance: number,
	plantChance: number,
	railingMaterial: string,
	awningColors: { string },
	plinthMaterial: string,
}

local Styles: { [string]: Style } = {
	Docks = {
		groundMaterial = "Slate",
		groundColor = "StoneWet",
		upperMaterial = "WoodPlanks",
		upperColor = "WoodWet",
		timberFrom = nil,
		corner = "corner_timber_h12",
		floorMaterial = "WoodPlanks",
		floorColor = "WoodLight",
		groundFloorMaterial = "WoodPlanks",
		roofMaterial = "RoofShingles",
		roofColors = { "RoofSlate", "RoofSlateDark", "WoodDark" },
		hipChance = 0.15,
		archChance = 0.1,
		windowChance = 0.45,
		cornice = false,
		runeband = false,
		balconyChance = 0.1,
		dormerChance = 0.1,
		chimneyChance = 0.6,
		bannerChance = 0.05,
		plantChance = 0.05,
		railingMaterial = "Wood",
		awningColors = { "ClothRed", "ClothNavy", "ClothOchre" },
		plinthMaterial = "Cobblestone",
	},
	Market = {
		groundMaterial = "Limestone",
		groundColor = "StoneLight",
		upperMaterial = "Plaster",
		upperColor = "Plaster",
		timberFrom = 1,
		corner = "corner_quoin_h12",
		floorMaterial = "WoodPlanks",
		floorColor = "WoodLight",
		groundFloorMaterial = "Slate",
		roofMaterial = "ClayRoofTiles",
		roofColors = { "RoofClay", "RoofSlate", "Terracotta" },
		hipChance = 0.25,
		archChance = 0.3,
		windowChance = 0.6,
		cornice = true,
		runeband = false,
		balconyChance = 0.25,
		dormerChance = 0.25,
		chimneyChance = 0.6,
		bannerChance = 0.2,
		plantChance = 0.15,
		railingMaterial = "Wood",
		awningColors = { "ClothRed", "ClothTeal", "ClothOchre", "ClothNavy" },
		plinthMaterial = "Cobblestone",
	},
	Residential = {
		groundMaterial = "Slate",
		groundColor = "Stone",
		upperMaterial = "Plaster",
		upperColor = "Plaster",
		timberFrom = 0,
		corner = "corner_quoin_h12",
		floorMaterial = "WoodPlanks",
		floorColor = "Wood",
		groundFloorMaterial = "WoodPlanks",
		roofMaterial = "Slate",
		roofColors = { "RoofSlate", "RoofSlateDark", "RoofClay" },
		hipChance = 0.2,
		archChance = 0.2,
		windowChance = 0.65,
		cornice = false,
		runeband = false,
		balconyChance = 0.35,
		dormerChance = 0.35,
		chimneyChance = 0.85,
		bannerChance = 0.05,
		plantChance = 0.2,
		railingMaterial = "Wood",
		awningColors = { "ClothTeal", "ClothRed" },
		plinthMaterial = "Cobblestone",
	},
	Noble = {
		groundMaterial = "Limestone",
		groundColor = "StoneLight",
		upperMaterial = "Limestone",
		upperColor = "StoneLight",
		timberFrom = nil,
		corner = "corner_quoin_h12",
		floorMaterial = "WoodPlanks",
		floorColor = "WoodDark",
		groundFloorMaterial = "Marble",
		roofMaterial = "Slate",
		roofColors = { "RoofSlateDark", "RoofSlate", "Verdigris" },
		hipChance = 0.65,
		archChance = 0.75,
		windowChance = 0.75,
		cornice = true,
		runeband = true,
		balconyChance = 0.4,
		dormerChance = 0.3,
		chimneyChance = 0.6,
		bannerChance = 0.45,
		plantChance = 0.18,
		railingMaterial = "Limestone",
		awningColors = { "ClothNavy", "ClothTeal" },
		plinthMaterial = "Granite",
	},
	Ruin = {
		groundMaterial = "Slate",
		groundColor = "StoneShadow",
		upperMaterial = "Slate",
		upperColor = "StoneShadow",
		timberFrom = nil,
		corner = "corner_quoin_h12",
		floorMaterial = "WoodPlanks",
		floorColor = "WoodWet",
		groundFloorMaterial = "Slate",
		roofMaterial = "Slate",
		roofColors = { "RoofSlateDark" },
		hipChance = 0,
		archChance = 0.6,
		windowChance = 0.5,
		cornice = false,
		runeband = false,
		balconyChance = 0,
		dormerChance = 0,
		chimneyChance = 0,
		bannerChance = 0,
		plantChance = 0,
		railingMaterial = "Limestone",
		awningColors = { "ClothNavy" },
		plinthMaterial = "Cobblestone",
	},
}

return Styles
