"""
Builds The Spire modular building kit in Blender and exports it.

Run headless (Blender 4.x or the `bpy` module):
    blender -b -P tools/blender/build_kit.py -- --repo .
    python  tools/blender/build_kit.py --repo .        (with the bpy wheel)

Outputs:
    assets/kit/fbx/<piece>.fbx                    one MeshPart per file, 1 unit = 1 stud
    assets/kit/kit.blend                          editable source scene, laid out on a grid
    assets/kit/kit_manifest.json                  machine-readable manifest
    src/ReplicatedStorage/Shared/Data/KitManifest.lua   generated Luau manifest
    src/ReplicatedStorage/Shared/Config/Palette.lua     generated palette
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import bpy  # noqa: E402

from kitlib import bbox_roblox, finalize  # noqa: E402
from palette import PALETTE  # noqa: E402
import pieces_arch  # noqa: E402,F401
import pieces_world  # noqa: E402,F401
from pieces_arch import REGISTRY  # noqa: E402

ROUGHNESS = {
    "Neon": 0.4, "Glass": 0.05, "Metal": 0.45, "CorrodedMetal": 0.7, "Marble": 0.35,
    "Fabric": 0.9, "LeafyGrass": 0.8, "Grass": 0.85,
}


def parse_args() -> argparse.Namespace:
    argv = sys.argv
    if "--" in argv:
        argv = argv[argv.index("--") + 1:]
    else:
        argv = argv[1:]
    p = argparse.ArgumentParser()
    p.add_argument("--repo", default=".")
    p.add_argument("--only", default="")
    p.add_argument("--no-fbx", action="store_true")
    return p.parse_args(argv)


def hex_rgb(h: str) -> tuple[float, float, float]:
    def lin(c: float) -> float:
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    return (lin(int(h[0:2], 16) / 255), lin(int(h[2:4], 16) / 255), lin(int(h[4:6], 16) / 255))


def get_material(roblox_mat: str, color_key: str) -> bpy.types.Material:
    name = f"{roblox_mat}_{color_key}"
    mat = bpy.data.materials.get(name)
    if mat:
        return mat
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    rgb = hex_rgb(PALETTE.get(color_key, "808080"))
    bsdf.inputs["Base Color"].default_value = (*rgb, 1.0)
    bsdf.inputs["Roughness"].default_value = ROUGHNESS.get(roblox_mat, 0.8)
    if roblox_mat == "Metal":
        bsdf.inputs["Metallic"].default_value = 0.8
    if roblox_mat == "Neon":
        bsdf.inputs["Emission Color"].default_value = (*rgb, 1.0)
        bsdf.inputs["Emission Strength"].default_value = 6.0
    if roblox_mat == "Glass":
        bsdf.inputs["Alpha"].default_value = 0.45
        mat.blend_method = "BLEND" if hasattr(mat, "blend_method") else mat.blend_method
    return mat


def lua_num(v: float) -> str:
    r = round(float(v), 3)
    if r == int(r):
        return str(int(r))
    return repr(r)


def lua_vec(v: list[float]) -> str:
    return "{" + ", ".join(lua_num(x) for x in v) + "}"


def emit_manifest_lua(entries: list[dict], path: str) -> None:
    lines = [
        "--!strict",
        "-- AUTO-GENERATED by tools/blender/build_kit.py. Do not edit by hand;",
        "-- change the Blender piece definitions and re-run the build instead.",
        "-- Every piece of The Spire building kit: bounding size/centre (studs, Roblox axes),",
        "-- default material and palette colour, collision mode, collider boxes,",
        "-- wall openings and named anchors used by the world planners.",
        "",
        "local Types = require(script.Parent.Parent.Types)",
        "",
        "local Manifest: { [string]: Types.KitPiece } = {",
    ]
    for e in entries:
        lines.append(f'\t["{e["id"]}"] = {{')
        lines.append(f'\t\tid = "{e["id"]}",')
        lines.append(f'\t\tcategory = "{e["category"]}",')
        lines.append(f'\t\tmaterial = "{e["material"]}",')
        lines.append(f'\t\tcolor = "{e["color"]}",')
        lines.append(f'\t\tcollision = "{e["collision"]}",')
        lines.append(f'\t\tstretch = "{e["stretch"]}",')
        lines.append(f'\t\tsize = {lua_vec(e["size"])},')
        lines.append(f'\t\tcenter = {lua_vec(e["center"])},')
        lines.append(f'\t\tfootprint = {lua_vec(e["footprint"])},')
        cols = ", ".join(
            f'{{ shape = "{c["shape"]}", c = {lua_vec(c["c"])}, s = {lua_vec(c["s"])}, ry = {lua_num(c["ry"])} }}'
            for c in e["colliders"]
        )
        lines.append(f"\t\tcolliders = {{ {cols} }},")
        ops = ", ".join(
            f'{{ kind = "{o["kind"]}", x0 = {lua_num(o["x0"])}, x1 = {lua_num(o["x1"])}, y0 = {lua_num(o["y0"])}, y1 = {lua_num(o["y1"])} }}'
            for o in e["openings"]
        )
        lines.append(f"\t\topenings = {{ {ops} }},")
        anc = ", ".join(f"{k} = {lua_vec(v)}" for k, v in sorted(e["anchors"].items()))
        lines.append(f"\t\tanchors = {{ {anc} }},")
        lines.append(f'\t\ttris = {e["tris"]},')
        lines.append("\t},")
    lines.append("}")
    lines.append("")
    lines.append("return Manifest")
    lines.append("")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def emit_palette_lua(path: str) -> None:
    lines = [
        "--!strict",
        "-- AUTO-GENERATED by tools/blender/build_kit.py from tools/blender/palette.py.",
        "-- Named colours used by the world kit, planners and world VFX.",
        "",
        "local Palette: { [string]: Color3 } = {",
    ]
    for k, v in PALETTE.items():
        lines.append(f'\t{k} = Color3.fromHex("#{v}"),')
    lines += ["}", "", "return Palette", ""]
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))


def main() -> None:
    args = parse_args()
    repo = os.path.abspath(args.repo)
    fbx_dir = os.path.join(repo, "assets", "kit", "fbx")
    os.makedirs(fbx_dir, exist_ok=True)
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.unit_settings.system = "NONE"

    ids = sorted(REGISTRY.keys())
    if args.only:
        ids = [i for i in ids if i.startswith(args.only)]
    entries: list[dict] = []
    t0 = time.time()
    for n, pid in enumerate(ids):
        b, meta = REGISTRY[pid]()
        assert meta.id == pid, f"piece id mismatch {pid} != {meta.id}"
        obj = finalize(pid, b, meta, n * 7919 + 13)
        obj.data.materials.append(get_material(meta.material, meta.color))
        size, center = bbox_roblox(obj)
        tris = sum(len(p.vertices) - 2 for p in obj.data.polygons)
        entries.append({
            "id": pid,
            "category": meta.category,
            "material": meta.material,
            "color": meta.color,
            "collision": meta.collision,
            "stretch": meta.stretch,
            "size": [round(s, 4) for s in size],
            "center": [round(c, 4) for c in center],
            "footprint": [round(f, 3) for f in (meta.footprint or size)],
            "colliders": [c.to_dict() for c in meta.colliders],
            "openings": [o.to_dict() for o in meta.openings],
            "anchors": {k: [round(x, 3) for x in v] for k, v in meta.anchors.items()},
            "tris": tris,
        })
        if not args.no_fbx:
            bpy.ops.object.select_all(action="DESELECT")
            obj.select_set(True)
            bpy.context.view_layer.objects.active = obj
            bpy.ops.export_scene.fbx(
                filepath=os.path.join(fbx_dir, pid + ".fbx"),
                use_selection=True,
                apply_unit_scale=True,
                global_scale=1.0,
                axis_forward="-Z",
                axis_up="Y",
                object_types={"MESH"},
                use_mesh_modifiers=True,
                mesh_smooth_type="FACE",
                add_leaf_bones=False,
                bake_anim=False,
                path_mode="STRIP",
            )
        # lay the scene out on a grid for the editable .blend
        col = n % 16
        row = n // 16
        obj.location = (col * 30.0, row * 30.0, 0.0) if max(size) < 28 else (col * 30.0, -400.0 - row * 120, 0.0)
        obj["roblox_material"] = meta.material
        obj["palette"] = meta.color
    print(f"built {len(entries)} pieces in {time.time() - t0:.1f}s, "
          f"{sum(e['tris'] for e in entries)} tris total")

    if not args.only:
        with open(os.path.join(repo, "assets", "kit", "kit_manifest.json"), "w", encoding="utf-8") as f:
            json.dump(entries, f, indent=1)
        emit_manifest_lua(entries, os.path.join(repo, "src", "ReplicatedStorage", "Shared", "Data", "KitManifest.lua"))
        emit_palette_lua(os.path.join(repo, "src", "ReplicatedStorage", "Shared", "Config", "Palette.lua"))
        bpy.ops.wm.save_as_mainfile(filepath=os.path.join(repo, "assets", "kit", "kit.blend"), compress=True)


if __name__ == "__main__":
    try:
        main()
    except Exception:  # bpy-as-module can hang on interpreter exit after an error
        import traceback
        traceback.print_exc()
        sys.stdout.flush()
        os._exit(1)
    sys.stdout.flush()
    os._exit(0)
